package pool

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
)

func newTestConfig(t *testing.T) *config.Config {
	t.Helper()
	root := t.TempDir()
	return &config.Config{
		Root:        root,
		TraefikDir:  filepath.Join(root, "traefik"),
		SitesDir:    filepath.Join(root, "sites"),
		NetworkName: "test_traefik",
	}
}

func TestFingerprintStable(t *testing.T) {
	a := Fingerprint("8.3", []string{"redis", "imagick"})
	b := Fingerprint("8.3", []string{"redis", "imagick"})
	if a != b {
		t.Errorf("Fingerprint not stable: %s != %s", a, b)
	}
	if len(a) != 12 {
		t.Errorf("Fingerprint length = %d, want 12", len(a))
	}
}

func TestFingerprintIgnoresExtensionOrder(t *testing.T) {
	a := Fingerprint("8.3", []string{"redis", "imagick"})
	b := Fingerprint("8.3", []string{"imagick", "redis"})
	if a != b {
		t.Errorf("Fingerprint order-sensitive: %s != %s", a, b)
	}
}

func TestFingerprintDistinguishesVersion(t *testing.T) {
	a := Fingerprint("8.3", []string{"redis"})
	b := Fingerprint("8.4", []string{"redis"})
	if a == b {
		t.Error("Fingerprint should differ across PHP versions")
	}
}

func TestFingerprintDistinguishesExtensions(t *testing.T) {
	a := Fingerprint("8.3", []string{"redis"})
	b := Fingerprint("8.3", []string{"redis", "imagick"})
	if a == b {
		t.Error("Fingerprint should differ across extension sets")
	}
}

func TestFingerprintEmptyExtensions(t *testing.T) {
	a := Fingerprint("8.3", nil)
	b := Fingerprint("8.3", []string{})
	if a != b {
		t.Errorf("Fingerprint nil vs empty: %s != %s", a, b)
	}
}

func TestFingerprintDoesNotMutateInput(t *testing.T) {
	ext := []string{"redis", "imagick", "bcmath"}
	original := append([]string(nil), ext...)
	_ = Fingerprint("8.3", ext)
	for i := range original {
		if ext[i] != original[i] {
			t.Fatalf("Fingerprint mutated input: %v -> %v", original, ext)
		}
	}
}

func TestContainerName(t *testing.T) {
	if got, want := ContainerName("abc123"), "srv-fpm-abc123"; got != want {
		t.Errorf("ContainerName = %q, want %q", got, want)
	}
}

func TestImageTag(t *testing.T) {
	if got, want := ImageTag("abc123"), "srv-php:abc123"; got != want {
		t.Errorf("ImageTag = %q, want %q", got, want)
	}
}

func TestDir(t *testing.T) {
	cfg := newTestConfig(t)
	got := Dir(cfg, "fp1")
	want := filepath.Join(cfg.Root, "fpm", "fp1")
	if got != want {
		t.Errorf("Dir = %q, want %q", got, want)
	}
}

func TestSiteMountPath(t *testing.T) {
	got := SiteMountPath("blog")
	want := constants.PHPSiteDocRootRoot + "/blog"
	if got != want {
		t.Errorf("SiteMountPath = %q, want %q", got, want)
	}
}

func TestWriteFilesCreatesAllArtifacts(t *testing.T) {
	cfg := newTestConfig(t)
	spec := Spec{
		PHPVersion: "8.3",
		Extensions: []string{"redis"},
		Members: []Member{
			{SiteName: "alpha", ProjectPath: "/srv/alpha"},
			{SiteName: "beta", ProjectPath: "/srv/beta"},
		},
	}
	if err := WriteFiles(cfg, spec, "FROM php", "memory_limit=512M\n", "[www]\n"); err != nil {
		t.Fatalf("WriteFiles err: %v", err)
	}
	fp := Fingerprint(spec.PHPVersion, spec.Extensions)
	dir := Dir(cfg, fp)

	for _, name := range []string{
		constants.PHPDockerfileFile,
		constants.PHPIniFile,
		constants.PHPFPMConfFile,
		"docker-compose.yml",
	} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("expected %s to exist: %v", name, err)
		}
	}

	composeBytes, err := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	if err != nil {
		t.Fatalf("read compose: %v", err)
	}
	if !strings.HasPrefix(string(composeBytes), "# Generated by srv") {
		t.Errorf("compose header missing; got: %q", string(composeBytes[:60]))
	}

	var parsed composeFile
	// Skip header lines (start at `services:`).
	yamlStart := strings.Index(string(composeBytes), "name:")
	if yamlStart < 0 {
		yamlStart = strings.Index(string(composeBytes), "services:")
	}
	if err := yaml.Unmarshal(composeBytes[yamlStart:], &parsed); err != nil {
		t.Fatalf("compose not valid YAML: %v", err)
	}
	if parsed.Name != constants.ComposeProjectName {
		t.Errorf("compose Name = %q, want %q", parsed.Name, constants.ComposeProjectName)
	}
	svc, ok := parsed.Services["fpm"]
	if !ok {
		t.Fatal("compose missing fpm service")
	}
	if svc.ContainerName != ContainerName(fp) {
		t.Errorf("ContainerName = %q, want %q", svc.ContainerName, ContainerName(fp))
	}
	if svc.Image != ImageTag(fp) {
		t.Errorf("Image = %q, want %q", svc.Image, ImageTag(fp))
	}
	// Two site volumes + 2 mount-bind volumes (php.ini, php-fpm.conf) = 4.
	if len(svc.Volumes) != 4 {
		t.Errorf("Volumes len = %d, want 4", len(svc.Volumes))
	}
}

func TestWriteFilesSortsMembers(t *testing.T) {
	cfg := newTestConfig(t)
	spec := Spec{
		PHPVersion: "8.3",
		Members: []Member{
			{SiteName: "zulu", ProjectPath: "/srv/zulu"},
			{SiteName: "alpha", ProjectPath: "/srv/alpha"},
			{SiteName: "mike", ProjectPath: "/srv/mike"},
		},
	}
	if err := WriteFiles(cfg, spec, "FROM", "", ""); err != nil {
		t.Fatalf("WriteFiles err: %v", err)
	}
	dir := Dir(cfg, Fingerprint(spec.PHPVersion, spec.Extensions))
	data, err := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	if err != nil {
		t.Fatalf("read compose: %v", err)
	}
	body := string(data)
	idxAlpha := strings.Index(body, "/srv/alpha")
	idxMike := strings.Index(body, "/srv/mike")
	idxZulu := strings.Index(body, "/srv/zulu")
	if !(idxAlpha < idxMike && idxMike < idxZulu) {
		t.Errorf("members not sorted: alpha=%d mike=%d zulu=%d", idxAlpha, idxMike, idxZulu)
	}
}

func TestWriteFilesMkdirError(t *testing.T) {
	// Point Root at a path that contains a file, blocking MkdirAll.
	tmp := t.TempDir()
	conflict := filepath.Join(tmp, "blocker")
	if err := os.WriteFile(conflict, []byte{}, 0o644); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{Root: conflict, NetworkName: "n"}
	err := WriteFiles(cfg, Spec{PHPVersion: "8.3"}, "", "", "")
	if err == nil {
		t.Fatal("expected mkdir error")
	}
	if !strings.Contains(err.Error(), "create pool dir") {
		t.Errorf("error %q missing wrapped context", err)
	}
}

func TestRemoveMissingDirOK(t *testing.T) {
	cfg := newTestConfig(t)
	if err := Remove(cfg, "doesnotexist"); err != nil {
		t.Errorf("Remove on missing dir returned err: %v", err)
	}
}

func TestRemoveExistingDir(t *testing.T) {
	cfg := newTestConfig(t)
	spec := Spec{PHPVersion: "8.3"}
	if err := WriteFiles(cfg, spec, "", "", ""); err != nil {
		t.Fatal(err)
	}
	fp := Fingerprint(spec.PHPVersion, spec.Extensions)
	dir := Dir(cfg, fp)
	if _, err := os.Stat(dir); err != nil {
		t.Fatalf("expected dir created: %v", err)
	}
	if err := Remove(cfg, fp); err != nil {
		t.Fatalf("Remove err: %v", err)
	}
	if _, err := os.Stat(dir); !os.IsNotExist(err) {
		t.Errorf("dir should be gone, stat err: %v", err)
	}
}

func TestBuildComposeNetworkRef(t *testing.T) {
	cfg := newTestConfig(t)
	cf := buildCompose(cfg, "fp", "/some/dir", nil)
	ref, ok := cf.Networks[constants.TraefikSubdir]
	if !ok {
		t.Fatalf("missing traefik network: %+v", cf.Networks)
	}
	if !ref.External {
		t.Error("network should be external")
	}
	if ref.Name != cfg.NetworkName {
		t.Errorf("network Name = %q, want %q", ref.Name, cfg.NetworkName)
	}
}

func TestBuildComposeHealthcheckIncludesPort(t *testing.T) {
	cfg := newTestConfig(t)
	cf := buildCompose(cfg, "fp", "/d", nil)
	svc := cf.Services["fpm"]
	if svc.HealthCheck == nil {
		t.Fatal("missing healthcheck")
	}
	joined := strings.Join(svc.HealthCheck.Test, " ")
	if !strings.Contains(joined, "9000") {
		t.Errorf("healthcheck missing FPM port: %v", svc.HealthCheck.Test)
	}
}
