# justfile for srv
# Run `just` to see all available commands

# Configuration
BINARY := "srv"
MKCERT_SRC := "third_party/mkcert"
MKCERT_BIN := "internal/mkcert/bin/mkcert"
MKCERT_VERSION_FILE := "internal/mkcert/version.go"

# Default recipe - list all available commands
default:
    @just --list

# =============================================================================
# Setup & Dependencies
# =============================================================================

# Check if required tools are installed
check-tools:
    #!/usr/bin/env bash
    command -v go >/dev/null 2>&1 || { echo "go is required but not installed." >&2; exit 1; }
    command -v golangci-lint >/dev/null 2>&1 || { echo "golangci-lint is required but not installed. See: https://golangci-lint.run/usage/install/" >&2; exit 1; }
    command -v gh >/dev/null 2>&1 || { echo "gh (GitHub CLI) is required but not installed. See: https://cli.github.com/" >&2; exit 1; }
    @echo "All required tools are installed!"

# =============================================================================
# Build Commands
# =============================================================================

# Build mkcert from the submodule source and embed it
mkcert:
    #!/usr/bin/env bash
    set -euo pipefail
    echo "Building mkcert from submodule..."
    mkdir -p "$(dirname '{{MKCERT_BIN}}')"
    MKCERT_VERSION=$(cd '{{MKCERT_SRC}}' && git describe --tags 2>/dev/null || echo "unknown")
    (cd '{{MKCERT_SRC}}' && CGO_ENABLED=0 go build \
      -ldflags "-X main.Version=$MKCERT_VERSION" \
      -o '../../{{MKCERT_BIN}}' .)
    printf '// Code generated by make mkcert — do not edit.\npackage mkcert\n\n// Version is the version of the embedded mkcert binary.\nconst Version = "%s"\n' \
      "$MKCERT_VERSION" > '{{MKCERT_VERSION_FILE}}'
    echo "Built mkcert $MKCERT_VERSION → {{MKCERT_BIN}}"

# Build the srv binary (builds mkcert first if not present)
build: mkcert
    go build -o {{BINARY}} .

# Build with version info embedded
build-release: mkcert
    #!/usr/bin/env bash
    VERSION=$(git describe --tags --always --dirty)
    COMMIT=$(git rev-parse --short HEAD)
    BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    go build -ldflags "-X github.com/stubbedev/srv/cmd.Version=$VERSION -X github.com/stubbedev/srv/cmd.Commit=$COMMIT -X github.com/stubbedev/srv/cmd.BuildDate=$BUILD_DATE" -o {{BINARY}} .

# Format Go code
fmt:
    go fmt ./...

# Run go vet
vet:
    go vet ./...

# Run golangci-lint on the codebase
lint:
    golangci-lint run ./...

# Run all checks (fmt, vet, lint, test) - useful for CI
check: fmt vet lint test

# Run tests (builds mkcert first if not present)
test: mkcert
    go test ./...

# Run tests with coverage
test-cover: mkcert
    go test -coverprofile=coverage.out ./...
    go tool cover -html=coverage.out -o coverage.html
    @echo "Coverage report: coverage.html"

# Download and tidy Go modules
mod:
    go mod download
    go mod tidy

# Remove build artifacts
clean:
    rm -f {{BINARY}}
    rm -f {{MKCERT_BIN}}
    rm -f {{MKCERT_VERSION_FILE}}
    rm -f coverage.out coverage.html

# Install binary to GOPATH/bin
install: build
    go install .
    @echo "Installed to $(go env GOPATH)/bin/{{BINARY}}"

# =============================================================================
# Release Commands
# =============================================================================

# Pre-release checks (clean working directory, on default branch)
_release-checks:
    #!/usr/bin/env bash
    set -euo pipefail
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    DEFAULT_BRANCH=$(git rev-parse --abbrev-ref origin/HEAD 2>/dev/null | sed 's|^origin/||' || git remote show origin 2>/dev/null | grep 'HEAD branch' | awk '{print $NF}')
    if [ -z "$DEFAULT_BRANCH" ]; then
        DEFAULT_BRANCH="main"
    fi
    if [ "$BRANCH" != "$DEFAULT_BRANCH" ]; then
        echo "Error: Not on default branch '$DEFAULT_BRANCH' (currently on '$BRANCH')." >&2
        exit 1
    fi
    just check
    if [ -n "$(git status --porcelain)" ]; then
        echo "Changes detected from formatting. Staging and committing..."
        git add -A
        git commit -m "chore: format code for release"
        echo "Committed formatting changes"
    fi

# Release a new major version (X.y.z -> X+1.0.0) with GitHub release
release-major: _release-checks
    #!/usr/bin/env bash
    set -euo pipefail
    CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
    CURRENT_VERSION=${CURRENT_TAG#v}
    MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
    NEW_MAJOR=$((MAJOR + 1))
    NEW_VERSION="v${NEW_MAJOR}.0.0"
    echo "Bumping from $CURRENT_TAG to $NEW_VERSION"
    git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
    git push origin "$NEW_VERSION"
    gh release create "$NEW_VERSION" --generate-notes
    echo "Released $NEW_VERSION"

# Release a new minor version (x.Y.z -> x.Y+1.0) with GitHub release
release-minor: _release-checks
    #!/usr/bin/env bash
    set -euo pipefail
    CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
    CURRENT_VERSION=${CURRENT_TAG#v}
    MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
    MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
    NEW_MINOR=$((MINOR + 1))
    NEW_VERSION="v${MAJOR}.${NEW_MINOR}.0"
    echo "Bumping from $CURRENT_TAG to $NEW_VERSION"
    git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
    git push origin "$NEW_VERSION"
    gh release create "$NEW_VERSION" --generate-notes
    echo "Released $NEW_VERSION"

# Release a new patch version (x.y.Z -> x.y.Z+1) with GitHub release
release-patch: _release-checks
    #!/usr/bin/env bash
    set -euo pipefail
    CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
    CURRENT_VERSION=${CURRENT_TAG#v}
    MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
    MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
    PATCH=$(echo "$CURRENT_VERSION" | cut -d. -f3)
    NEW_PATCH=$((PATCH + 1))
    NEW_VERSION="v${MAJOR}.${MINOR}.${NEW_PATCH}"
    echo "Bumping from $CURRENT_TAG to $NEW_VERSION"
    git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
    git push origin "$NEW_VERSION"
    gh release create "$NEW_VERSION" --generate-notes
    echo "Released $NEW_VERSION"

# Preview what versions would be created (dry-run)
release-preview:
    #!/usr/bin/env bash
    CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
    CURRENT_VERSION=${CURRENT_TAG#v}
    MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
    MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
    PATCH=$(echo "$CURRENT_VERSION" | cut -d. -f3)
    echo "Current: $CURRENT_TAG"
    echo "  major: v$((MAJOR + 1)).0.0"
    echo "  minor: v${MAJOR}.$((MINOR + 1)).0"
    echo "  patch: v${MAJOR}.${MINOR}.$((PATCH + 1))"

# =============================================================================
# Maintenance Commands
# =============================================================================

# Update mkcert submodule to latest upstream, rebuild, and commit
update-mkcert:
    #!/usr/bin/env bash
    set -euo pipefail
    echo "Updating mkcert submodule to latest..."
    git submodule update --remote {{MKCERT_SRC}}
    MKCERT_COMMIT=$(cd {{MKCERT_SRC}} && git rev-parse HEAD)
    echo "Updated to $MKCERT_COMMIT"
    sed -i 's|url = "github:FiloSottile/mkcert/[^"]*"|url = "github:FiloSottile/mkcert/'"$MKCERT_COMMIT"'"|' flake.nix
    nix flake update mkcert
    just mkcert
    git add {{MKCERT_SRC}} flake.nix flake.lock
    git commit -m "chore: update mkcert to $MKCERT_COMMIT"
