.PHONY: build test clean mkcert

BINARY := srv
MKCERT_BIN_DIR := internal/mkcert/bin
MKCERT_VERSION_FILE := internal/mkcert/version.go

## Fetch the latest mkcert release tag and download platform binaries.
mkcert:
	@echo "Fetching latest mkcert version..."
	$(eval MKCERT_VERSION := $(shell curl -fsSL https://api.github.com/repos/FiloSottile/mkcert/releases/latest | grep '"tag_name"' | sed 's/.*"tag_name": *"\(.*\)".*/\1/'))
	@[ -n "$(MKCERT_VERSION)" ] || (echo "error: could not determine latest mkcert version" && exit 1)
	@echo "Downloading mkcert $(MKCERT_VERSION)..."
	@mkdir -p $(MKCERT_BIN_DIR)
	@curl -fsSL https://github.com/FiloSottile/mkcert/releases/download/$(MKCERT_VERSION)/mkcert-$(MKCERT_VERSION)-linux-amd64  -o $(MKCERT_BIN_DIR)/mkcert-linux-amd64
	@curl -fsSL https://github.com/FiloSottile/mkcert/releases/download/$(MKCERT_VERSION)/mkcert-$(MKCERT_VERSION)-linux-arm64  -o $(MKCERT_BIN_DIR)/mkcert-linux-arm64
	@curl -fsSL https://github.com/FiloSottile/mkcert/releases/download/$(MKCERT_VERSION)/mkcert-$(MKCERT_VERSION)-linux-arm    -o $(MKCERT_BIN_DIR)/mkcert-linux-arm
	@curl -fsSL https://github.com/FiloSottile/mkcert/releases/download/$(MKCERT_VERSION)/mkcert-$(MKCERT_VERSION)-darwin-amd64 -o $(MKCERT_BIN_DIR)/mkcert-darwin-amd64
	@curl -fsSL https://github.com/FiloSottile/mkcert/releases/download/$(MKCERT_VERSION)/mkcert-$(MKCERT_VERSION)-darwin-arm64 -o $(MKCERT_BIN_DIR)/mkcert-darwin-arm64
	@printf '// Code generated by make mkcert — do not edit.\npackage mkcert\n\n// Version is the version of the embedded mkcert binary.\nconst Version = "$(MKCERT_VERSION)"\n' > $(MKCERT_VERSION_FILE)
	@echo "Done. mkcert $(MKCERT_VERSION) binaries written to $(MKCERT_BIN_DIR)"

## Build the srv binary. Downloads mkcert binaries first if not present.
build: $(MKCERT_BIN_DIR)/mkcert-linux-amd64
	go build -o $(BINARY) .

## Run tests.
test: $(MKCERT_BIN_DIR)/mkcert-linux-amd64
	go test ./...

## Remove build artifacts and downloaded mkcert binaries.
clean:
	rm -f $(BINARY)
	rm -rf $(MKCERT_BIN_DIR)
	rm -f $(MKCERT_VERSION_FILE)

## Download mkcert if the sentinel binary is missing.
$(MKCERT_BIN_DIR)/mkcert-linux-amd64:
	@$(MAKE) mkcert
