.PHONY: build test clean mkcert update-mkcert

BINARY         := srv
MKCERT_SRC     := third_party/mkcert
MKCERT_BIN     := internal/mkcert/bin/mkcert
MKCERT_VERSION_FILE := internal/mkcert/version.go

## Update mkcert to the latest upstream commit, rebuild the embedded binary,
## refresh flake.lock, and commit everything in one step.
update-mkcert:
	@echo "Updating mkcert submodule to latest..."
	git submodule update --remote third_party/mkcert
	$(eval MKCERT_COMMIT := $(shell git -C $(MKCERT_SRC) rev-parse HEAD))
	@echo "Updated to $(MKCERT_COMMIT)"
	@sed -i 's|url = "github:FiloSottile/mkcert/[^"]*"|url = "github:FiloSottile/mkcert/$(MKCERT_COMMIT)"|' flake.nix
	nix flake update mkcert
	@$(MAKE) mkcert
	git add third_party/mkcert flake.nix flake.lock
	git commit -m "chore: update mkcert to $(MKCERT_COMMIT)"

## Build mkcert from the submodule source and embed it.
mkcert: $(MKCERT_BIN)

$(MKCERT_BIN): $(MKCERT_SRC)/main.go
	@echo "Building mkcert from submodule..."
	@mkdir -p $(dir $(MKCERT_BIN))
	$(eval MKCERT_VERSION := $(shell git -C $(MKCERT_SRC) describe --tags 2>/dev/null || echo "unknown"))
	cd $(MKCERT_SRC) && CGO_ENABLED=0 go build \
	  -ldflags "-X main.Version=$(MKCERT_VERSION)" \
	  -o ../../$(MKCERT_BIN) .
	@printf '// Code generated by make mkcert — do not edit.\npackage mkcert\n\n// Version is the version of the embedded mkcert binary.\nconst Version = "%s"\n' \
	  "$(MKCERT_VERSION)" > $(MKCERT_VERSION_FILE)
	@echo "Built mkcert $(MKCERT_VERSION) → $(MKCERT_BIN)"

## Build the srv binary. Builds mkcert first if not present.
build: $(MKCERT_BIN)
	go build -o $(BINARY) .

## Run tests. Builds mkcert first if not present.
test: $(MKCERT_BIN)
	go test ./...

## Remove build artifacts.
clean:
	rm -f $(BINARY)
	rm -f $(MKCERT_BIN)
	rm -f $(MKCERT_VERSION_FILE)
