// Package proxy provides a thin metadata layer that sits alongside the
// existing Traefik file-provider YAML for `srv proxy`-managed entries. Its
// purpose is narrow: persist the host + aliases + wildcard flag + extra
// routes that `srv route` needs to attach. The Traefik routing YAML itself
// (proxy-<name>.yml under TraefikConfDir) is still written by the existing
// proxy command — this layer does not replace it, only augment it.
package proxy

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
	"github.com/stubbedev/srv/internal/site"
	"github.com/stubbedev/srv/internal/traefik"
)

// Metadata captures everything `srv route` needs to know about a proxy:
// the canonical domain (+ aliases), local-CA flag, wildcard flag, and any
// attached routes. Stored at ~/.config/srv/proxies/<name>/metadata.yml.
type Metadata struct {
	// metadata.yml schema version (1 = current).
	SchemaVersion int `yaml:"schema_version,omitempty"`
	// Proxy name; also the basename of the generated proxy-<name>.yml.
	Name string `yaml:"name"`
	// All hostnames routed to this proxy; the first entry is canonical.
	Domains []string `yaml:"domains"`
	// Match apex + one-level subdomains (*.example.com); local proxies only.
	Wildcard bool `yaml:"wildcard,omitempty"`
	// Use a locally-issued (mkcert) SSL certificate instead of Let's Encrypt.
	IsLocal bool `yaml:"is_local,omitempty"`
	// Extra Traefik routers (path-prefix / regex-rewrite splits) attached via `srv route`.
	Routes []site.Route `yaml:"routes,omitempty"`
}

const currentSchemaVersion = 1

// proxiesDir returns ~/.config/srv/proxies.
func proxiesDir(cfg *config.Config) string {
	return filepath.Join(cfg.Root, "proxies")
}

// metadataPath returns the metadata.yml path for a given proxy.
func metadataPath(cfg *config.Config, name string) string {
	return filepath.Join(proxiesDir(cfg), name, constants.MetadataFile)
}

// Exists reports whether the named proxy has a metadata sidecar.
func Exists(name string) bool {
	cfg, err := config.Load()
	if err != nil {
		return false
	}
	_, err = os.Stat(metadataPath(cfg, name))
	return err == nil
}

// Read returns the proxy's metadata, or (nil, nil) when it does not exist.
func Read(name string) (*Metadata, error) {
	cfg, err := config.Load()
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(metadataPath(cfg, name))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var m Metadata
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse proxy metadata: %w", err)
	}
	return &m, nil
}

// Write persists the proxy metadata. The schema version is stamped on first
// write.
func Write(meta Metadata) error {
	if meta.Name == "" {
		return fmt.Errorf("proxy metadata is missing name")
	}
	cfg, err := config.Load()
	if err != nil {
		return err
	}
	if meta.SchemaVersion == 0 {
		meta.SchemaVersion = currentSchemaVersion
	}
	dir := filepath.Join(proxiesDir(cfg), meta.Name)
	if err := os.MkdirAll(dir, constants.DirPermDefault); err != nil {
		return fmt.Errorf("create proxy metadata dir: %w", err)
	}
	data, err := yaml.Marshal(&meta)
	if err != nil {
		return fmt.Errorf("marshal proxy metadata: %w", err)
	}
	header := "# yaml-language-server: $schema=" + constants.ProxyMetadataSchemaURL + "\n" +
		"# Proxy metadata — generated by srv\n"
	return os.WriteFile(metadataPath(cfg, meta.Name), append([]byte(header), data...), constants.FilePermDefault)
}

// Remove deletes the proxy's metadata directory. Safe to call when the
// proxy has no metadata sidecar yet.
func Remove(name string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}
	dir := filepath.Join(proxiesDir(cfg), name)
	if err := os.RemoveAll(dir); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// ListNames returns the names of every proxy with a metadata sidecar, for
// shell completion and similar helpers.
func ListNames() []string {
	cfg, err := config.Load()
	if err != nil {
		return nil
	}
	entries, err := os.ReadDir(proxiesDir(cfg))
	if err != nil {
		return nil
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if Exists(e.Name()) {
			out = append(out, e.Name())
		}
	}
	return out
}

// Reload re-renders the routes-<name>.yml Traefik file for a proxy from its
// metadata.Routes. Called after `srv route add/remove` to push the routes
// out without touching the base proxy-<name>.yml Traefik config. Returns
// nil when the proxy has no metadata yet (nothing to reload).
func Reload(name string) error {
	meta, err := Read(name)
	if err != nil {
		return err
	}
	if meta == nil {
		return fmt.Errorf("proxy not found: %s", name)
	}
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	set := traefik.SiteRouteSet{
		SiteName: name,
		Domains:  meta.Domains,
		Wildcard: meta.Wildcard,
		IsLocal:  meta.IsLocal,
	}
	for _, r := range meta.Routes {
		upstream, uerr := traefik.ResolveUpstreamURL(r.Upstream.Kind, r.Upstream.Container, r.Upstream.URL, r.Upstream.Port)
		if uerr != nil {
			return fmt.Errorf("route %q: %w", r.ID, uerr)
		}
		preserve := true
		if r.PreserveHost != nil {
			preserve = *r.PreserveHost
		}
		set.Routes = append(set.Routes, traefik.RouteSpec{
			ID:                 r.ID,
			Path:               r.Path,
			PathRegex:          r.PathRegex,
			Rewrite:            r.Rewrite,
			UpstreamURL:        upstream,
			PreserveHost:       preserve,
			Priority:           r.Priority,
			InsecureSkipVerify: r.Upstream.InsecureSkipVerify,
		})
	}
	if err := traefik.WriteRoutesConfig(cfg, set); err != nil {
		return err
	}
	return traefik.UpdateDynamicConfig()
}

// DescribeName returns a friendly description used in CLI errors / completions.
func DescribeName(meta *Metadata) string {
	if meta == nil {
		return ""
	}
	if len(meta.Domains) == 0 {
		return meta.Name
	}
	return meta.Name + " (" + strings.Join(meta.Domains, ", ") + ")"
}
