package traefik

import (
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/shell"
)

// CheckMkcert verifies mkcert is installed and provides installation instructions if not.
func CheckMkcert() error {
	if !shell.Exists("mkcert") {
		if runtime.GOOS == "darwin" {
			return fmt.Errorf("mkcert is not installed.\n  Install with: brew install mkcert")
		}
		return fmt.Errorf("mkcert is not installed.\n  See: https://github.com/FiloSottile/mkcert#installation")
	}
	return nil
}

// IsCAInstalled checks if the mkcert CA is installed.
func IsCAInstalled() bool {
	output, err := shell.MkcertQuiet("-CAROOT")
	if err != nil {
		return false
	}
	caRoot := strings.TrimSpace(string(output))
	if caRoot == "" {
		return false
	}
	_, err = os.Stat(filepath.Join(caRoot, "rootCA.pem"))
	return err == nil
}

// InstallCA installs the mkcert CA certificate.
func InstallCA() error {
	if !shell.Exists("mkcert") {
		return fmt.Errorf("mkcert is not installed.\n  Install it first: https://github.com/FiloSottile/mkcert#installation")
	}

	if err := shell.Mkcert("-install"); err != nil {
		return fmt.Errorf("failed to install mkcert CA: %w", err)
	}

	return nil
}

// LocalCertsExist checks if local SSL certificates exist for a domain.
func LocalCertsExist(domain string) bool {
	cfg, err := config.Load()
	if err != nil {
		return false
	}
	certFile := filepath.Join(cfg.LocalCertsDir(), domain+".crt")
	keyFile := filepath.Join(cfg.LocalCertsDir(), domain+".key")
	_, certErr := os.Stat(certFile)
	_, keyErr := os.Stat(keyFile)
	return certErr == nil && keyErr == nil
}

// RemoveLocalCerts removes SSL certificates for a specific domain.
func RemoveLocalCerts(domain string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}
	certFile := filepath.Join(cfg.LocalCertsDir(), domain+".crt")
	keyFile := filepath.Join(cfg.LocalCertsDir(), domain+".key")
	os.Remove(certFile)
	os.Remove(keyFile)
	return nil
}

// GenerateLocalCert generates an SSL certificate for a specific domain using mkcert.
func GenerateLocalCert(domain string) error {
	if err := CheckMkcert(); err != nil {
		return err
	}

	cfg, err := config.Load()
	if err != nil {
		return err
	}

	certDir := cfg.LocalCertsDir()
	if err := os.MkdirAll(certDir, 0o755); err != nil {
		return fmt.Errorf("failed to create certs directory: %w", err)
	}

	certFile := filepath.Join(certDir, domain+".crt")
	keyFile := filepath.Join(certDir, domain+".key")

	args := []string{
		"-cert-file", certFile,
		"-key-file", keyFile,
		domain,
	}

	if err := shell.Mkcert(args...); err != nil {
		return fmt.Errorf("failed to generate certificate for %s: %w", domain, err)
	}

	return nil
}

// EnsureLocalCert generates an SSL certificate for a domain if it doesn't exist.
func EnsureLocalCert(domain string) error {
	if LocalCertsExist(domain) {
		return nil
	}
	return GenerateLocalCert(domain)
}

// UpdateDynamicConfig regenerates the Traefik dynamic config with all local domain certs.
func UpdateDynamicConfig() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	certDir := cfg.LocalCertsDir()

	// Find all .crt files in the local certs directory
	var certs []string
	entries, err := os.ReadDir(certDir)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to read certs directory: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".crt") {
			domain := strings.TrimSuffix(name, ".crt")
			keyFile := filepath.Join(certDir, domain+".key")
			if _, err := os.Stat(keyFile); err == nil {
				certs = append(certs, domain)
			}
		}
	}

	// Build dynamic config
	var content strings.Builder
	content.WriteString("# Dynamic Traefik configuration - generated by srv\n")
	content.WriteString("# Do not edit manually\n")
	content.WriteString("tls:\n")

	if len(certs) == 0 {
		content.WriteString("  certificates: []\n")
	} else {
		content.WriteString("  certificates:\n")
		for _, domain := range certs {
			content.WriteString(fmt.Sprintf("    - certFile: /etc/traefik/certs/local/%s.crt\n", domain))
			content.WriteString(fmt.Sprintf("      keyFile: /etc/traefik/certs/local/%s.key\n", domain))
		}
	}

	dynamicPath := filepath.Join(cfg.TraefikConfDir(), "traefik-dynamic.yml")
	if err := os.WriteFile(dynamicPath, []byte(content.String()), 0o644); err != nil {
		return fmt.Errorf("failed to write dynamic config: %w", err)
	}

	return nil
}

// CertInfo holds certificate expiry information.
type CertInfo struct {
	Domain    string
	Exists    bool
	ExpiresAt time.Time
	DaysLeft  int
	IsExpired bool
}

// GetLocalCertInfo returns information about a specific local SSL certificate.
func GetLocalCertInfo(domain string) CertInfo {
	cfg, err := config.Load()
	if err != nil {
		return CertInfo{Domain: domain}
	}

	certFile := filepath.Join(cfg.LocalCertsDir(), domain+".crt")
	info := parseCertFile(certFile)
	info.Domain = domain
	return info
}

// ListLocalCerts returns information about all local SSL certificates.
func ListLocalCerts() []CertInfo {
	cfg, err := config.Load()
	if err != nil {
		return nil
	}

	certDir := cfg.LocalCertsDir()
	entries, err := os.ReadDir(certDir)
	if err != nil {
		return nil
	}

	var certs []CertInfo
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".crt") {
			domain := strings.TrimSuffix(name, ".crt")
			certs = append(certs, GetLocalCertInfo(domain))
		}
	}
	return certs
}

// parseCertFile reads a PEM certificate file and returns expiry info.
func parseCertFile(certPath string) CertInfo {
	data, err := os.ReadFile(certPath)
	if err != nil {
		return CertInfo{Exists: false}
	}

	block, _ := pem.Decode(data)
	if block == nil {
		return CertInfo{Exists: true}
	}

	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return CertInfo{Exists: true}
	}

	now := time.Now()
	daysLeft := int(cert.NotAfter.Sub(now).Hours() / 24)

	return CertInfo{
		Exists:    true,
		ExpiresAt: cert.NotAfter,
		DaysLeft:  daysLeft,
		IsExpired: now.After(cert.NotAfter),
	}
}
