// Package traefik — lifecycle.go owns the container lifecycle and dashboard
// proxy. Bundles IsRunning / IsDNSRunning + the start/restart/reset
// operations + the traefik.local dashboard proxy setup, all of which only
// concern themselves with running containers rather than config files on
// disk.
package traefik

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
	"github.com/stubbedev/srv/internal/docker"
)

// IsRunning checks if Traefik container is running.
func IsRunning() bool {
	return docker.IsContainerRunning(docker.ContainerTraefik)
}

// IsDNSRunning checks if the DNS container is running.
func IsDNSRunning() bool {
	return docker.IsContainerRunning(docker.ContainerDNS)
}

// DashboardURL returns the Traefik dashboard URL (plain HTTP, local port).
func DashboardURL() string {
	return fmt.Sprintf("%s%s:%d/dashboard/", constants.SchemeHTTPPrefix, constants.LocalhostIP, constants.PortDashboard)
}

// DashboardLocalURL returns the HTTPS dashboard URL via the traefik.local proxy.
func DashboardLocalURL() string {
	return fmt.Sprintf("https://%s/dashboard/", constants.TraefikDashboardDomain)
}

// SetupDashboardProxy creates (or refreshes) a local HTTPS proxy for the
// Traefik dashboard at traefik.local, including a mkcert SSL certificate
// and DNS registration. Idempotent: calling it a second time renews the
// cert if needed but does not fail if the proxy config already exists.
func SetupDashboardProxy() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	domain := constants.TraefikDashboardDomain
	name := constants.TraefikDashboardProxyName
	proxySiteName := "_proxy-" + name

	if _, err := EnsureLocalCert(proxySiteName, []string{domain}, false); err != nil {
		return fmt.Errorf("failed to generate certificate for %s: %w", domain, err)
	}
	if err := RegisterLocalDomain(domain, false); err != nil {
		return fmt.Errorf("failed to register DNS for %s: %w", domain, err)
	}
	if err := writeDashboardProxyConfig(cfg, name, domain); err != nil {
		return err
	}
	if err := UpdateDynamicConfig(); err != nil {
		return fmt.Errorf("failed to update dynamic config: %w", err)
	}
	return nil
}

// writeDashboardProxyConfig writes the Traefik router/service YAML for the
// dashboard proxy to the conf directory.
func writeDashboardProxyConfig(cfg *config.Config, name, domain string) error {
	type Server struct {
		URL string `yaml:"url"`
	}
	type LoadBalancer struct {
		Servers []Server `yaml:"servers"`
	}
	type Service struct {
		LoadBalancer LoadBalancer `yaml:"loadBalancer"`
	}
	type Router struct {
		Rule        string    `yaml:"rule"`
		EntryPoints []string  `yaml:"entryPoints"`
		Service     string    `yaml:"service"`
		TLS         *struct{} `yaml:"tls,omitempty"`
	}
	type HTTP struct {
		Routers  map[string]Router  `yaml:"routers"`
		Services map[string]Service `yaml:"services"`
	}
	type ProxyConfig struct {
		HTTP HTTP `yaml:"http"`
	}

	routerName := constants.ProxyConfigPrefix + name
	targetURL := fmt.Sprintf("%s%s:%d", constants.SchemeHTTPPrefix, constants.LocalhostAlias, constants.PortDashboard)

	proxyConfig := ProxyConfig{
		HTTP: HTTP{
			Routers: map[string]Router{
				routerName: {
					Rule:        fmt.Sprintf("Host(`%s`)", domain),
					EntryPoints: []string{constants.EntryPointWebsecure},
					Service:     routerName,
					TLS:         &struct{}{},
				},
			},
			Services: map[string]Service{
				routerName: {
					LoadBalancer: LoadBalancer{
						Servers: []Server{{URL: targetURL}},
					},
				},
			},
		},
	}

	data, err := yaml.Marshal(&proxyConfig)
	if err != nil {
		return fmt.Errorf("failed to marshal dashboard proxy config: %w", err)
	}

	content := fmt.Sprintf(
		"# Proxy configuration for %s - generated by srv\n# Domain: %s\n%s",
		name, domain, data,
	)

	proxyFile := filepath.Join(cfg.TraefikConfDir(), constants.ProxyConfigPrefix+name+constants.ExtYAML)
	return os.WriteFile(proxyFile, []byte(content), constants.FilePermDefault)
}

// RestartTraefik restarts the Traefik container.
func RestartTraefik() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}
	return docker.Compose(cfg.TraefikDir, "restart")
}

// RecreateTraefik recreates Traefik containers with the latest image.
func RecreateTraefik() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}
	return docker.Compose(cfg.TraefikDir, "up", "-d", "--force-recreate")
}

// Reset removes the entire srv configuration directory for a fresh start.
// Stops Traefik containers first (best-effort), removes the config tree, and
// clears the config cache so the next Load() rereads from disk.
func Reset() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}
	if IsRunning() || IsDNSRunning() {
		_ = docker.Compose(cfg.TraefikDir, "down")
	}
	if err := os.RemoveAll(cfg.Root); err != nil {
		return fmt.Errorf("failed to remove config directory: %w", err)
	}
	config.ResetCache()
	return nil
}
