// Package traefik — proxy_redirect.go renders the Traefik file-provider configs
// for `srv proxy add` and `srv redirect add` (HTTP variant). These used to live
// in cmd/ where each hand-declared its own copy of the dynamic-config structs;
// they now share the typed model in dynamic.go alongside the site and route
// writers. The cmd package keeps thin wrappers that build the input struct.
package traefik

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
	"github.com/stubbedev/srv/internal/fsutil"
)

// ProxyRoute describes a reverse proxy to render as a Traefik file config.
type ProxyRoute struct {
	Name      string // short proxy name (file is proxy-<name>.yml)
	Domain    string // hostname clients hit
	TargetURL string // upstream URL (http://host:port or http://container:port)
	Container string // optional container name, recorded in the header comment
	Wildcard  bool   // match apex + one-level subdomains
	// FallbackURL turns the service into Traefik's native failover (v3.7+):
	// 5xx responses and dial failures re-proxy to this URL.
	FallbackURL string
	// FallbackDial bounds the connect phase to the primary before a dial
	// failure fails over. Empty means the Traefik default; srv passes the
	// user's --fallback-timeout through.
	FallbackDial string
}

// WriteProxyConfig renders proxy-<name>.yml. The config terminates TLS with a
// file-provider (mkcert) certificate and forwards to TargetURL. With a
// FallbackURL the service becomes a failover pair: primary + fallback
// load balancers under a failover wrapper with errors.status 500-599, so a
// 5xx response from the primary (or its connection failing, which Traefik
// surfaces as 502) transparently re-serves from the fallback. An https
// fallback gets an insecureSkipVerify transport — the fallback host is
// operator-configured and its cert may not match a dev chain.
func WriteProxyConfig(cfg *config.Config, p ProxyRoute) error {
	key := constants.ProxyConfigPrefix + p.Name
	router := dynRouter{
		Rule:        BuildHostRule([]string{p.Domain}, p.Wildcard),
		EntryPoints: []string{constants.EntryPointWebsecure},
		Service:     key,
		TLS:         localTLS(),
	}

	services := map[string]dynService{
		key: {LoadBalancer: &dynLoadBalancer{Servers: []dynServer{{URL: p.TargetURL}}}},
	}
	var transports map[string]dynServersTransport

	if p.FallbackURL != "" {
		dial := p.FallbackDial
		if dial == "" {
			dial = constants.FallbackTimeoutDefault
		}
		primaryTransport := key + "-transport"
		transports = map[string]dynServersTransport{
			primaryTransport: {
				ForwardingTimeouts: &dynForwardingTimeouts{DialTimeout: dial},
			},
		}

		primary, fallback := key+"-primary", key+"-fallback"
		services = map[string]dynService{
			key: {
				Failover: &dynFailover{
					Service:  primary,
					Fallback: fallback,
					Errors:   &dynFailoverErrors{Status: []string{"500-599"}},
				},
			},
			primary: {
				LoadBalancer: &dynLoadBalancer{
					Servers:          []dynServer{{URL: p.TargetURL}},
					ServersTransport: primaryTransport,
				},
			},
			fallback: {LoadBalancer: &dynLoadBalancer{Servers: []dynServer{{URL: p.FallbackURL}}}},
		}
		if strings.HasPrefix(p.FallbackURL, "https://") {
			fallbackTransport := key + "-fb-transport"
			transports[fallbackTransport] = dynServersTransport{InsecureSkipVerify: true}
			services[fallback] = dynService{
				LoadBalancer: &dynLoadBalancer{
					Servers:          []dynServer{{URL: p.FallbackURL}},
					ServersTransport: fallbackTransport,
				},
			}
		}
	}

	conf := DynConfig{
		HTTP: dynHTTP{
			Routers:           map[string]dynRouter{key: router},
			Services:          services,
			ServersTransports: transports,
		},
	}

	data, err := MarshalDynConfig(conf)
	if err != nil {
		return fmt.Errorf("failed to marshal proxy config: %w", err)
	}

	var content string
	if p.Container != "" {
		content = fmt.Sprintf("# Proxy configuration for %s - generated by srv\n# Domain: %s\n# Container: %s\n%s", p.Name, p.Domain, p.Container, data)
	} else {
		content = fmt.Sprintf("# Proxy configuration for %s - generated by srv\n# Domain: %s\n%s", p.Name, p.Domain, data)
	}

	// Atomic write: Traefik watches this file.
	proxyFile := filepath.Join(cfg.TraefikConfDir(), constants.ProxyConfigPrefix+p.Name+constants.ExtYAML)
	return fsutil.AtomicWriteFile(proxyFile, []byte(content), constants.FilePermDefault)
}

// HTTPRedirect describes an HTTP 301/302 redirect to render as a Traefik config.
type HTTPRedirect struct {
	Name      string // short redirect name (file is redirect-<name>.yml)
	Domain    string // source hostname
	To        string // normalized target URL
	Permanent bool   // 301 when true, 302 when false
	Wildcard  bool   // match apex + one-level subdomains
}

// WriteRedirectConfig renders redirect-<name>.yml: a regex middleware that
// rewrites any request on the source host to the target URL, bound to both
// entrypoints so plain-HTTP requests redirect in one hop.
func WriteRedirectConfig(cfg *config.Config, r HTTPRedirect) error {
	routerKey := constants.RedirectConfigPrefix + r.Name
	mwKey := routerKey + "-mw"
	svcKey := routerKey + "-noop"

	// Capture the path+query (everything after the host's leading slash) so it
	// can be appended to the normalized target. The leading slash is rebuilt in
	// the replacement so a target without a path lands on `/<path>`.
	mw := dynMiddleware{
		RedirectRegex: &dynRedirectRegex{
			Regex:       `^https?://[^/]+/?(.*)$`,
			Replacement: r.To + "/$1",
			Permanent:   r.Permanent,
		},
	}

	hostRule := BuildHostRule([]string{r.Domain}, r.Wildcard)
	httpsRouter := dynRouter{
		Rule:        hostRule,
		EntryPoints: []string{constants.EntryPointWebsecure},
		Service:     svcKey,
		Middlewares: []string{mwKey},
		TLS:         localTLS(),
	}
	httpRouter := dynRouter{
		Rule:        hostRule,
		EntryPoints: []string{constants.EntryPointWeb},
		Service:     svcKey,
		Middlewares: []string{mwKey},
	}

	conf := DynConfig{
		HTTP: dynHTTP{
			Routers: map[string]dynRouter{
				routerKey:           httpsRouter,
				routerKey + "-http": httpRouter,
			},
			// Traefik requires a service on every router even when a middleware
			// terminates the request first. Point at a black hole so a
			// misconfigured middleware fails loudly instead of silently
			// forwarding traffic somewhere.
			Services: map[string]dynService{
				svcKey: {LoadBalancer: &dynLoadBalancer{Servers: []dynServer{{URL: "http://127.0.0.1:1"}}}},
			},
			Middlewares: map[string]dynMiddleware{mwKey: mw},
		},
	}

	data, err := MarshalDynConfig(conf)
	if err != nil {
		return fmt.Errorf("failed to marshal redirect config: %w", err)
	}

	code := "301"
	if !r.Permanent {
		code = "302"
	}
	content := fmt.Sprintf("# Redirect configuration for %s - generated by srv\n# Domain: %s\n# Target: %s\n# Code:   %s\n%s",
		r.Name, r.Domain, r.To, code, data)

	// Atomic write: Traefik watches this file.
	redirectFile := filepath.Join(cfg.TraefikConfDir(), constants.RedirectConfigPrefix+r.Name+constants.ExtYAML)
	return fsutil.AtomicWriteFile(redirectFile, []byte(content), constants.FilePermDefault)
}
