package traefik

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
)

// BuildHostRule returns the Traefik router rule for one or more domains. With
// wildcard=true, the rule matches the apex domain plus any single-level
// subdomain for each domain — mirroring the SAN coverage of mkcert's
// `*.domain` wildcard certificates. Multiple domains are OR-joined.
func BuildHostRule(domains []string, wildcard bool) string {
	parts := make([]string, 0, len(domains))
	for _, d := range domains {
		if d == "" {
			continue
		}
		if wildcard {
			parts = append(parts, fmt.Sprintf("Host(`%s`) || HostRegexp(`^[^.]+\\.%s$`)", d, regexp.QuoteMeta(d)))
		} else {
			parts = append(parts, fmt.Sprintf("Host(`%s`)", d))
		}
	}
	return strings.Join(parts, " || ")
}

// SiteRouteConfig holds the configuration for a site's Traefik routing.
type SiteRouteConfig struct {
	Name        string   // Site name (used for router/service names)
	Domains     []string // All hostnames; Domains[0] is canonical
	ServiceName string   // Container name to route to
	Port        int      // Port the service listens on
	IsLocal     bool     // Whether to use local SSL (mkcert) or Let's Encrypt
	Wildcard    bool     // Match apex + one-level subdomains (apex only when false)
}

// WriteSiteRouteConfig creates a Traefik file provider config for a site.
// This allows routing to Docker compose services without modifying the project's compose files.
// The config is written to ~/.config/srv/traefik/conf/site-{name}.yml
func WriteSiteRouteConfig(cfg *config.Config, route SiteRouteConfig) error {
	// Build the config using proper types to avoid YAML injection
	type Server struct {
		URL string `yaml:"url"`
	}
	type LoadBalancer struct {
		Servers []Server `yaml:"servers"`
	}
	type Service struct {
		LoadBalancer LoadBalancer `yaml:"loadBalancer"`
	}
	type TLSConfig struct {
		CertResolver string `yaml:"certResolver,omitempty"`
	}
	type Router struct {
		Rule        string     `yaml:"rule"`
		EntryPoints []string   `yaml:"entryPoints"`
		Service     string     `yaml:"service"`
		TLS         *TLSConfig `yaml:"tls,omitempty"`
	}
	type HTTP struct {
		Routers  map[string]Router  `yaml:"routers"`
		Services map[string]Service `yaml:"services"`
	}
	type SiteConfig struct {
		HTTP HTTP `yaml:"http"`
	}

	routerName := constants.SiteConfigPrefix + route.Name
	serviceName := constants.SiteConfigPrefix + route.Name

	// Route to the service via docker network
	// The URL format is http://{container_name}:{port}
	// We use the container name directly since Traefik resolves via Docker network
	serviceURL := fmt.Sprintf("http://%s:%d", route.ServiceName, route.Port)

	router := Router{
		Rule:        BuildHostRule(route.Domains, route.Wildcard),
		EntryPoints: []string{constants.EntryPointWebsecure},
		Service:     serviceName,
	}

	if route.IsLocal {
		// Local SSL uses file provider certificates (no certResolver)
		router.TLS = &TLSConfig{}
	} else {
		// Production uses Let's Encrypt
		router.TLS = &TLSConfig{CertResolver: constants.CertResolverLetsEncrypt}
	}

	siteConfig := SiteConfig{
		HTTP: HTTP{
			Routers: map[string]Router{
				routerName: router,
			},
			Services: map[string]Service{
				serviceName: {
					LoadBalancer: LoadBalancer{
						Servers: []Server{{URL: serviceURL}},
					},
				},
			},
		},
	}

	data, err := yaml.Marshal(&siteConfig)
	if err != nil {
		return fmt.Errorf("failed to marshal site config: %w", err)
	}

	// Add header comment with metadata
	primary := ""
	if len(route.Domains) > 0 {
		primary = route.Domains[0]
	}
	header := fmt.Sprintf(`# Site configuration for %s - generated by srv
# Domain: %s
# Container: %s
# Port: %d
`, route.Name, primary, route.ServiceName, route.Port)

	content := header + string(data)

	siteFile := filepath.Join(cfg.TraefikConfDir(), constants.SiteConfigPrefix+route.Name+constants.ExtYAML)
	return os.WriteFile(siteFile, []byte(content), constants.FilePermDefault)
}

// RemoveSiteRouteConfig removes the Traefik file provider config for a site.
func RemoveSiteRouteConfig(cfg *config.Config, name string) error {
	siteFile := filepath.Join(cfg.TraefikConfDir(), constants.SiteConfigPrefix+name+constants.ExtYAML)
	if err := os.Remove(siteFile); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove site config: %w", err)
	}
	return nil
}

// RouteConfig represents the structure of a Traefik file provider config.
// It is used for parsing both site and proxy route YAML files and is shared
// with cmd/proxy.go to avoid the struct being defined twice.
type RouteConfig struct {
	HTTP struct {
		Routers map[string]struct {
			Rule string `yaml:"rule"`
		} `yaml:"routers"`
		Services map[string]struct {
			LoadBalancer struct {
				Servers []struct {
					URL string `yaml:"url"`
				} `yaml:"servers"`
			} `yaml:"loadBalancer"`
		} `yaml:"services"`
	} `yaml:"http"`
}

// ExtractDomainFromRule extracts the first domain from a Traefik Host rule.
// Rule format: Host(`example.com`) or Host(`example.com`, `www.example.com`)
// or Host(`a`) || Host(`b`) for multi-domain routers.
func ExtractDomainFromRule(rule string) string {
	domains := ExtractDomainsFromRule(rule)
	if len(domains) == 0 {
		return ""
	}
	return domains[0]
}

// ExtractDomainsFromRule extracts all Host(`…`) domains from a Traefik router
// rule. Returns nil if the rule contains no Host literals.
func ExtractDomainsFromRule(rule string) []string {
	const prefix = "Host(`"
	var out []string
	rest := rule
	for {
		idx := strings.Index(rest, prefix)
		if idx == -1 {
			break
		}
		rest = rest[idx+len(prefix):]
		end := strings.Index(rest, "`")
		if end == -1 {
			break
		}
		// Inside Host(`a`, `b`, ...) — peel any extra backticked entries too.
		first := rest[:end]
		out = append(out, first)
		rest = rest[end+1:]
	}
	return out
}

// ReadSiteRouteDomain reads the domain from a site route config file.
func ReadSiteRouteDomain(cfg *config.Config, name string) string {
	siteFile := filepath.Join(cfg.TraefikConfDir(), constants.SiteConfigPrefix+name+constants.ExtYAML)
	data, err := os.ReadFile(siteFile)
	if err != nil {
		return ""
	}

	// Parse the YAML structure
	var config RouteConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return ""
	}

	// Extract domain from first router's rule
	for _, router := range config.HTTP.Routers {
		if domain := ExtractDomainFromRule(router.Rule); domain != "" {
			return domain
		}
	}

	return ""
}
