package traefik

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/docker"
	"github.com/stubbedev/srv/internal/shell"
)

// ContainerStatic is the name of the static file server container.
const ContainerStatic = "srv-static"

// ImageNginx is the nginx image used for static file serving.
const ImageNginx = "nginx:alpine"

// StaticServerDockerCompose generates docker-compose config for the static server.
func StaticServerDockerCompose(networkName string, parkedPaths []string) string {
	var volumes strings.Builder

	// Always create a default empty volume mount
	volumes.WriteString("      - ./static-default:/srv/default:ro\n")

	// Mount each parked directory
	for i, path := range parkedPaths {
		volumes.WriteString(fmt.Sprintf("      - %s:/srv/parked%d:ro\n", path, i))
	}

	// Build labels for Traefik routing - one router per parked directory's subdirs
	// We use a wildcard approach: *.test routes to this container
	// Note: Traefik v3 uses plain regex syntax for HostRegexp (not {name:pattern} from v2)
	labels := `      - "traefik.enable=true"
      - "traefik.http.routers.srv-static.rule=HostRegexp(` + "`" + `^[a-z0-9-]+\\.test$` + "`" + `)"
      - "traefik.http.routers.srv-static.entrypoints=websecure"
      - "traefik.http.routers.srv-static.tls=true"
      - "traefik.http.routers.srv-static.priority=10"
      - "traefik.http.services.srv-static.loadbalancer.server.port=80"`

	return fmt.Sprintf(`# Auto-generated by srv - do not edit manually
# Static file server for parked directories

services:
  static:
    image: %s
    container_name: %s
    restart: unless-stopped
    volumes:
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf:ro
%s    labels:
%s
    networks:
      - traefik

networks:
  traefik:
    name: %s
    external: true
`, ImageNginx, ContainerStatic, volumes.String(), labels, networkName)
}

// GenerateStaticNginxConf generates a more sophisticated nginx config
// that properly routes subdomains to the correct parked directory.
func GenerateStaticNginxConf(parkedPaths []string) string {
	var config strings.Builder

	config.WriteString(`# Auto-generated by srv - do not edit manually
# Maps subdomains to parked directories

map $host $site_root {
    default /srv/default;
}

server {
    listen 80;
    server_name ~^(?<subdomain>[a-z0-9-]+)\.test$;
    
    # Default root (will be overridden by location blocks)
    root /srv/default;
    index index.html index.htm;
    
    # Try each parked location for the subdomain
`)

	for i := range parkedPaths {
		config.WriteString(fmt.Sprintf(`
    location @parked%d {
        root /srv/parked%d/$subdomain;
        try_files $uri $uri/ /index.html /index.htm =404;
    }
`, i, i))
	}

	config.WriteString(`
    location / {
        # Try to serve from parked directories in order
`)

	if len(parkedPaths) > 0 {
		// Build a chain of try_files with named locations
		config.WriteString("        set $root_found '';\n")
		for i := range parkedPaths {
			config.WriteString(fmt.Sprintf(`
        # Check parked path %d
        if (-d /srv/parked%d/$subdomain) {
            set $root_found /srv/parked%d/$subdomain;
        }
`, i, i, i))
		}
		config.WriteString(`
        # Use found root or default
        if ($root_found != '') {
            root $root_found;
        }
        
        try_files $uri $uri/ /index.html /index.htm =404;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
`)
	} else {
		config.WriteString(`        return 404 'No parked directories configured. Use srv park add <path>';
`)
	}

	config.WriteString(`    }
    
    # Error handling
    error_page 404 @not_found;
    location @not_found {
        default_type text/html;
        return 404 '<!DOCTYPE html><html><head><title>404 Not Found</title><style>body{font-family:system-ui,sans-serif;max-width:600px;margin:100px auto;padding:20px;text-align:center}h1{color:#e53e3e}code{background:#f1f1f1;padding:2px 8px;border-radius:4px}</style></head><body><h1>Site Not Found</h1><p>No parked site found for <code>$subdomain.test</code></p><p>Create a directory named <code>$subdomain</code> in one of your parked paths.</p></body></html>';
    }
}
`)

	return config.String()
}

// UpdateStaticServer updates or creates the static server configuration.
func UpdateStaticServer(parkedPaths []string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	staticDir := filepath.Join(cfg.TraefikDir, "static")
	if err := os.MkdirAll(staticDir, 0o755); err != nil {
		return fmt.Errorf("failed to create static directory: %w", err)
	}

	// Create default directory for when no parks exist
	defaultDir := filepath.Join(cfg.TraefikDir, "static-default")
	if err := os.MkdirAll(defaultDir, 0o755); err != nil {
		return fmt.Errorf("failed to create default static directory: %w", err)
	}

	// Write default index.html
	defaultIndex := `<!DOCTYPE html>
<html>
<head>
    <title>srv Static Server</title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 600px; margin: 100px auto; padding: 20px; text-align: center; }
        h1 { color: #3182ce; }
        code { background: #f1f1f1; padding: 2px 8px; border-radius: 4px; }
    </style>
</head>
<body>
    <h1>srv Static Server</h1>
    <p>This server hosts parked directories.</p>
    <p>Use <code>srv park add /path/to/sites</code> to park a directory.</p>
</body>
</html>`
	if err := os.WriteFile(filepath.Join(defaultDir, "index.html"), []byte(defaultIndex), 0o644); err != nil {
		return fmt.Errorf("failed to write default index.html: %w", err)
	}

	// Write nginx config
	nginxConf := GenerateStaticNginxConf(parkedPaths)
	nginxPath := filepath.Join(cfg.TraefikDir, "nginx-static.conf")
	if err := os.WriteFile(nginxPath, []byte(nginxConf), 0o644); err != nil {
		return fmt.Errorf("failed to write nginx config: %w", err)
	}

	// Write docker-compose for static server
	composeYML := StaticServerDockerCompose(cfg.NetworkName, parkedPaths)
	composePath := filepath.Join(cfg.TraefikDir, "docker-compose.static.yml")
	if err := os.WriteFile(composePath, []byte(composeYML), 0o644); err != nil {
		return fmt.Errorf("failed to write static docker-compose: %w", err)
	}

	// Generate wildcard certificate for *.test if mkcert is available
	if err := CheckMkcert(); err == nil && IsCAInstalled() {
		if !LocalCertsExist("_wildcard.test") {
			certDir := cfg.LocalCertsDir()
			certFile := filepath.Join(certDir, "_wildcard.test.crt")
			keyFile := filepath.Join(certDir, "_wildcard.test.key")

			if err := shell.Mkcert("-cert-file", certFile, "-key-file", keyFile, "*.test"); err == nil {
				// Update dynamic config to include the wildcard cert
				// Ignore error: non-critical, config will be updated on next operation
				_ = UpdateDynamicConfig() //nolint:errcheck
			}
		}
	}

	return nil
}

// StartStaticServer starts the static file server container.
func StartStaticServer() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	composePath := filepath.Join(cfg.TraefikDir, "docker-compose.static.yml")
	if _, err := os.Stat(composePath); os.IsNotExist(err) {
		return fmt.Errorf("static server not configured. Run 'srv park add <path>' first")
	}

	return docker.Compose(cfg.TraefikDir, "-f", "docker-compose.static.yml", "up", "-d")
}

// StopStaticServer stops the static file server container.
func StopStaticServer() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	composePath := filepath.Join(cfg.TraefikDir, "docker-compose.static.yml")
	if _, err := os.Stat(composePath); os.IsNotExist(err) {
		return nil // Not configured, nothing to stop
	}

	return docker.Compose(cfg.TraefikDir, "-f", "docker-compose.static.yml", "down")
}

// RestartStaticServer restarts the static file server to pick up config changes.
func RestartStaticServer() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	composePath := filepath.Join(cfg.TraefikDir, "docker-compose.static.yml")
	if _, err := os.Stat(composePath); os.IsNotExist(err) {
		return nil // Not configured
	}

	// Recreate to pick up volume changes
	return docker.Compose(cfg.TraefikDir, "-f", "docker-compose.static.yml", "up", "-d", "--force-recreate")
}

// IsStaticServerRunning checks if the static server container is running.
func IsStaticServerRunning() bool {
	return docker.IsContainerRunning(ContainerStatic)
}
