// Package traefik handles Traefik configuration generation and management.
package traefik

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hashicorp/go-envparse"
	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
	"github.com/stubbedev/srv/internal/docker"
	"github.com/stubbedev/srv/internal/platform"
)

// TraefikYML is the static Traefik configuration template.
const TraefikYML = `api:
  dashboard: true
  insecure: true
  disableDashboardAd: true

log:
  level: INFO

accessLog:
  filePath: /etc/traefik/logs/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "200-299"
      - "400-599"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

tracing:
  serviceName: traefik

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  internal:
    address: ":88"

providers:
  docker:
    exposedByDefault: false
    network: "{{NETWORK}}"
  file:
    directory: /etc/traefik/conf
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{EMAIL}}"
      storage: /etc/traefik/certs/acme.json
      httpChallenge:
        entryPoint: web
`

// TraefikDynamicYML is the dynamic Traefik configuration template.
// This is the base template; domain-specific certs are added dynamically.
const TraefikDynamicYML = `# Dynamic Traefik configuration
# Domain-specific TLS certificates are added below by srv
tls:
  certificates: []
`

// dockerComposeTemplate is the Traefik docker-compose template.
// Use DockerComposeTemplate() to get the template with variables substituted.
// DNS_HTTP_USER and DNS_HTTP_PASS are generated once at init time and persisted
// to env.traefik so they remain stable across subsequent calls to EnsureConfig.
const dockerComposeTemplate = `services:
  traefik:
    image: {{TRAEFIK_IMAGE}}
    container_name: {{TRAEFIK_CONTAINER}}
    restart: unless-stopped{{NETWORK_MODE}}{{PORTS}}{{EXTRA_HOSTS}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf:/etc/traefik/conf:ro
      - ./certs:/etc/traefik/certs
      - ./logs:/etc/traefik/logs
      - {{SITES_DIR}}:/etc/traefik/sites:ro{{NETWORKS}}

  dns:
    image: {{DNS_IMAGE}}
    container_name: {{DNS_CONTAINER}}
    restart: unless-stopped
    ports:
      - "127.0.0.1:53:53/udp"
    environment:
      - HTTP_USER={{DNS_HTTP_USER}}
      - HTTP_PASS={{DNS_HTTP_PASS}}
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dnsmasq.hosts:/etc/dnsmasq.hosts:ro
    logging:
      driver: none{{HOST_RELAY}}

networks:
  traefik:
    name: {{NETWORK}}
    external: true
`

// generateRandomString generates a cryptographically random hex string of the
// specified length. Returns an error if the system's random source is unavailable
// so the caller can fail the specific operation without crashing the process.
func generateRandomString(length int) (string, error) {
	b := make([]byte, length/2+1)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("crypto/rand unavailable: %w", err)
	}
	return hex.EncodeToString(b)[:length], nil
}

// DockerComposeTemplate returns the docker-compose template with all variables substituted.
// dnsUser and dnsPass are the dnsmasq HTTP credentials; they must be loaded or
// generated by the caller (see loadOrGenerateDNSCredentials) to avoid rotation on
// every call.
// Credential values are YAML-single-quote-escaped so that any special characters
// in future credential formats cannot break the YAML structure.
//
// On Linux, Traefik uses network_mode: host to access localhost services directly.
// This allows 'srv proxy' to work with services bound to 127.0.0.1 without code changes.
// The custom Docker network is still used for container-to-container communication
// (containers connect to it and publish ports that Traefik can reach via localhost).
func DockerComposeTemplate(networkName, sitesDir, dnsUser, dnsPass string) string {
	// On Linux, use host networking to access localhost services directly
	// On Mac/Windows, Docker Desktop provides host.docker.internal automatically
	networkMode := ""
	ports := `
    ports:
      - "80:80"
      - "443:443"
      - "88:88"
      - "8080:8080"`
	extraHosts := ""
	networks := `
    networks:
      - traefik`
	hostRelay := ""

	if platform.IsLinux() {
		// Use host network mode on Linux - this gives Traefik access to localhost
		// Traefik can still proxy to Docker containers via their published ports on localhost
		networkMode = `
    network_mode: host`
		// Host mode doesn't need port mappings (Traefik binds directly to host ports)
		ports = ""
		// Host mode can't use custom networks, but Traefik can reach containers via Docker API
		networks = ""
		// No need for extra_hosts with host mode
		extraHosts = ""
	}

	r := strings.NewReplacer(
		"{{TRAEFIK_IMAGE}}", docker.ImageTraefik,
		"{{DNS_IMAGE}}", docker.ImageDNS,
		"{{TRAEFIK_CONTAINER}}", docker.ContainerTraefik,
		"{{DNS_CONTAINER}}", docker.ContainerDNS,
		"{{NETWORK_MODE}}", networkMode,
		"{{PORTS}}", ports,
		"{{EXTRA_HOSTS}}", extraHosts,
		"{{NETWORKS}}", networks,
		"{{HOST_RELAY}}", hostRelay,
		"{{NETWORK}}", networkName,
		"{{SITES_DIR}}", sitesDir,
		// Single-quote the credential values so YAML-special chars are safe.
		// Single quotes in the value itself are escaped as '' per YAML spec.
		"{{DNS_HTTP_USER}}", yamlSingleQuote(dnsUser),
		"{{DNS_HTTP_PASS}}", yamlSingleQuote(dnsPass),
	)
	return r.Replace(dockerComposeTemplate)
}

// yamlSingleQuote wraps s in YAML single quotes, escaping any literal single
// quotes inside the value by doubling them per the YAML 1.2 spec.
func yamlSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// writeTraefikCompose regenerates traefik/docker-compose.yml from the current
// template. It is idempotent — the content is stable across calls — and exists
// so callers other than EnsureConfig (notably ReloadDNS) can pick up template
// changes such as a newly added bind mount without a full reinstall.
func writeTraefikCompose(cfg *config.Config) error {
	dnsUser, dnsPass, err := loadOrGenerateDNSCredentials(cfg.EnvTraefikPath())
	if err != nil {
		return err
	}
	composeYML := DockerComposeTemplate(cfg.NetworkName, cfg.SitesDir, dnsUser, dnsPass)
	return os.WriteFile(cfg.TraefikComposePath(), []byte(composeYML), constants.FilePermDefault)
}

// readEnvFile reads the env.traefik file and returns its key/value pairs.
// Returns an empty map if the file does not exist.
func readEnvFile(path string) map[string]string {
	f, err := os.Open(path)
	if err != nil {
		return map[string]string{}
	}
	defer func() { _ = f.Close() }()
	parsed, err := envparse.Parse(f)
	if err != nil {
		return map[string]string{}
	}
	return parsed
}

// writeEnvFile persists a key/value map to path as a .env file atomically
// with 0600 permissions so credentials are not world-readable.
func writeEnvFile(path string, envMap map[string]string) error {
	// Produce deterministic output by sorting keys.
	keys := make([]string, 0, len(envMap))
	for k := range envMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var content strings.Builder
	for _, k := range keys {
		fmt.Fprintf(&content, "%s=%s\n", k, envMap[k])
	}

	// Write atomically so a crash mid-write never produces a partial file.
	tmp := path + constants.ExtTmp
	if err := os.WriteFile(tmp, []byte(content.String()), constants.FilePermACME); err != nil {
		return fmt.Errorf("failed to write env file: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("failed to install env file: %w", err)
	}
	return nil
}

// loadOrGenerateDNSCredentials reads DNS_HTTP_USER and DNS_HTTP_PASS from the
// env.traefik file. If either value is missing it generates fresh credentials,
// persists them alongside any existing keys, and returns the values.
func loadOrGenerateDNSCredentials(envPath string) (user, pass string, err error) {
	envMap := readEnvFile(envPath)

	user = envMap[constants.EnvDNSHTTPUser]
	pass = envMap[constants.EnvDNSHTTPPass]

	if user != "" && pass != "" {
		return user, pass, nil
	}

	// Generate missing values.
	if user == "" {
		user, err = generateRandomString(constants.DNSUserLength)
		if err != nil {
			return "", "", fmt.Errorf("failed to generate DNS user: %w", err)
		}
	}
	if pass == "" {
		pass, err = generateRandomString(constants.DNSPassLength)
		if err != nil {
			return "", "", fmt.Errorf("failed to generate DNS password: %w", err)
		}
	}

	// Persist all keys including the newly generated credentials.
	envMap[constants.EnvDNSHTTPUser] = user
	envMap[constants.EnvDNSHTTPPass] = pass

	if writeErr := writeEnvFile(envPath, envMap); writeErr != nil {
		return "", "", fmt.Errorf("failed to persist DNS credentials: %w", writeErr)
	}

	return user, pass, nil
}

// DnsmasqConf is the initial dnsmasq configuration (no domains).
// Domains are added dynamically via UpdateDnsmasqConfig(). It must stay
// byte-identical to buildDnsmasqConf(nil, {GoogleDNS1, GoogleDNS2}) so a fresh
// install does not see a spurious config change on the first domain add.
//
// Exact (non-wildcard) domains live in the hostsdir, which dnsmasq auto-reloads
// without a restart; only wildcard domains land in this file.
const DnsmasqConf = `# Local domains managed by srv
# Do not edit manually - changes will be overwritten

# Exact (non-wildcard) domains are auto-reloaded from this directory
hostsdir=/etc/dnsmasq.hosts

# No wildcard domains registered

# Forward all other queries to upstream DNS
server=8.8.8.8
server=8.8.4.4

# Don't read /etc/resolv.conf
no-resolv
`

// EnsureConfig ensures all Traefik configuration files exist.
// If traefik.yml exists, it merges user customizations with the template.
func EnsureConfig(email string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	// Create directories
	dirs := []string{
		cfg.TraefikDir,
		cfg.TraefikConfDir(),
		filepath.Join(cfg.TraefikDir, constants.CertsSubdir),
		filepath.Join(cfg.TraefikDir, constants.LogsSubdir),
		filepath.Join(cfg.TraefikDir, constants.DnsmasqHostsDir),
		cfg.SitesDir,
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, constants.DirPermDefault); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	// Write or merge traefik.yml
	traefikPath := filepath.Join(cfg.TraefikConfDir(), "traefik.yml")
	if err := writeOrMergeTraefikYML(traefikPath, cfg.NetworkName, email); err != nil {
		return err
	}

	// Write traefik-dynamic.yml
	dynamicPath := filepath.Join(cfg.TraefikConfDir(), "traefik-dynamic.yml")
	if err := os.WriteFile(dynamicPath, []byte(TraefikDynamicYML), constants.FilePermDefault); err != nil {
		return fmt.Errorf("failed to write traefik-dynamic.yml: %w", err)
	}

	// Load or generate DNS credentials once; they are persisted to env.traefik so
	// subsequent calls to EnsureConfig reuse the same values instead of rotating them.
	dnsUser, dnsPass, err := loadOrGenerateDNSCredentials(cfg.EnvTraefikPath())
	if err != nil {
		return err
	}

	// Write docker-compose.yml
	composeYML := DockerComposeTemplate(cfg.NetworkName, cfg.SitesDir, dnsUser, dnsPass)
	composePath := cfg.TraefikComposePath()
	if err := os.WriteFile(composePath, []byte(composeYML), constants.FilePermDefault); err != nil {
		return fmt.Errorf("failed to write docker-compose.yml: %w", err)
	}

	// Write dnsmasq.conf — preserve registered domains on re-init.
	// On first run the file does not exist, so write the blank template.
	// On subsequent runs call UpdateDnsmasqConfig so existing domain
	// entries are regenerated from local-domains.txt rather than wiped.
	dnsmasqPath := filepath.Join(cfg.TraefikDir, constants.DnsmasqConfFile)
	if _, statErr := os.Stat(dnsmasqPath); os.IsNotExist(statErr) {
		if err := os.WriteFile(dnsmasqPath, []byte(DnsmasqConf), constants.FilePermDefault); err != nil {
			return fmt.Errorf("failed to write dnsmasq.conf: %w", err)
		}
		// Seed an (empty but non-empty-file) hosts file so dnsmasq's hostsdir
		// has something to read on first start.
		hostsPath := filepath.Join(cfg.TraefikDir, constants.DnsmasqHostsDir, constants.DnsmasqHostsFile)
		if err := os.WriteFile(hostsPath, []byte(buildDnsmasqHosts(nil)), constants.FilePermDefault); err != nil {
			return fmt.Errorf("failed to write dnsmasq hosts file: %w", err)
		}
	} else {
		if err := UpdateDnsmasqConfig(); err != nil {
			return fmt.Errorf("failed to refresh dnsmasq.conf: %w", err)
		}
	}

	// Create acme.json with proper permissions
	acmePath := filepath.Join(cfg.TraefikDir, constants.CertsSubdir, constants.ACMEJSONFile)
	if _, err := os.Stat(acmePath); os.IsNotExist(err) {
		if err := os.WriteFile(acmePath, []byte("{}"), constants.FilePermACME); err != nil {
			return fmt.Errorf("failed to create acme.json: %w", err)
		}
	}

	return nil
}

// managedTraefikSections are the top-level keys that srv owns. The template
// is authoritative for these; any user edits in the existing file are replaced.
var managedTraefikSections = []string{"providers", "certificatesResolvers"}

// writeOrMergeTraefikYML writes the traefik.yml file, merging with existing config if present.
// Managed sections (providers, certificatesResolvers) are always taken from the template.
// entryPoints are merged: user additions preserved, web/websecure/internal ensured from template.
// All other top-level keys (api, log, metrics, tracing, experimental, tls, …) are preserved
// verbatim from the existing file. If the existing file is malformed YAML, the call fails
// rather than silently overwriting it — the user's customizations are too valuable to drop.
func writeOrMergeTraefikYML(path, networkName, email string) error {
	// Prepare the template with substitutions
	templateYML := strings.ReplaceAll(TraefikYML, "{{NETWORK}}", networkName)
	templateYML = strings.ReplaceAll(templateYML, "{{EMAIL}}", email)

	// Check if file exists
	existingData, err := os.ReadFile(path)
	if err != nil {
		// File doesn't exist, write fresh
		if os.IsNotExist(err) {
			return os.WriteFile(path, []byte(templateYML), constants.FilePermDefault)
		}
		return fmt.Errorf("failed to read existing traefik.yml: %w", err)
	}

	// Parse existing config — refuse to clobber a file we cannot parse.
	var existing map[string]any
	if err := yaml.Unmarshal(existingData, &existing); err != nil {
		return fmt.Errorf("existing traefik.yml at %s is not valid YAML: %w\n(refusing to overwrite — fix the file or delete it to regenerate)", path, err)
	}

	// Parse template config
	var template map[string]any
	if err := yaml.Unmarshal([]byte(templateYML), &template); err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	// Merge configs
	merged := mergeTraefikConfigs(existing, template)

	// Marshal back to YAML
	output, err := yaml.Marshal(merged)
	if err != nil {
		return fmt.Errorf("failed to marshal merged config: %w", err)
	}

	return os.WriteFile(path, output, constants.FilePermDefault)
}

// mergeTraefikConfigs merges existing config with template.
// - Managed sections (providers, certificatesResolvers) are taken from template
// - entryPoints are merged: user additions preserved, web/websecure ensured from template
// - Every other top-level key in either map is preserved (existing wins on conflict)
func mergeTraefikConfigs(existing, template map[string]any) map[string]any {
	result := make(map[string]any, len(existing)+len(template))

	managed := make(map[string]struct{}, len(managedTraefikSections)+1)
	for _, k := range managedTraefikSections {
		managed[k] = struct{}{}
	}
	managed["entryPoints"] = struct{}{}

	// Preserve every non-managed key from the template first (so it acts as a
	// default), then let the existing file override — user edits win.
	for k, v := range template {
		if _, isManaged := managed[k]; isManaged {
			continue
		}
		result[k] = v
	}
	for k, v := range existing {
		if _, isManaged := managed[k]; isManaged {
			continue
		}
		result[k] = v
	}

	// Managed sections - always use template
	for _, section := range managedTraefikSections {
		if val, ok := template[section]; ok {
			result[section] = val
		}
	}

	// entryPoints - merge: preserve user additions, ensure web/websecure from template
	result["entryPoints"] = mergeEntryPoints(existing, template)

	return result
}

// mergeEntryPoints merges entryPoints configs.
// Preserves user-added entrypoints, ensures web/websecure/internal exist from template.
func mergeEntryPoints(existing, template map[string]any) map[string]any {
	result := make(map[string]any)

	// Start with existing entryPoints (preserves user additions)
	if existingEP, ok := existing["entryPoints"].(map[string]any); ok {
		maps.Copy(result, existingEP)
	}

	// Ensure the srv-managed entrypoints from the template are present.
	if templateEP, ok := template["entryPoints"].(map[string]any); ok {
		for _, name := range []string{"web", "websecure", constants.EntryPointInternal} {
			if v, ok := templateEP[name]; ok {
				result[name] = v
			}
		}
	}

	return result
}
