// Package traefik handles Traefik configuration generation and management.
package traefik

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/charmbracelet/huh"
	"github.com/hashicorp/go-envparse"
	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
	"github.com/stubbedev/srv/internal/docker"
	"github.com/stubbedev/srv/internal/shell"
)

// TraefikYML is the static Traefik configuration template.
const TraefikYML = `api:
  dashboard: true
  insecure: true
  disableDashboardAd: true

log:
  level: INFO

accessLog:
  filePath: /etc/traefik/logs/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "200-299"
      - "400-599"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

tracing:
  serviceName: traefik

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  internal:
    address: ":88"

providers:
  docker:
    exposedByDefault: false
    network: "{{NETWORK}}"
  file:
    directory: /etc/traefik/conf
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{EMAIL}}"
      storage: /etc/traefik/certs/acme.json
      httpChallenge:
        entryPoint: web
`

// TraefikDynamicYML is the dynamic Traefik configuration template.
// This is the base template; domain-specific certs are added dynamically.
const TraefikDynamicYML = `# Dynamic Traefik configuration
# Domain-specific TLS certificates are added below by srv
tls:
  certificates: []
`

// dockerComposeTemplate is the Traefik docker-compose template.
// Use DockerComposeTemplate() to get the template with variables substituted.
// DNS_HTTP_USER and DNS_HTTP_PASS are generated once at init time and persisted
// to env.traefik so they remain stable across subsequent calls to EnsureConfig.
const dockerComposeTemplate = `services:
  traefik:
    image: {{TRAEFIK_IMAGE}}
    container_name: {{TRAEFIK_CONTAINER}}
    restart: unless-stopped{{NETWORK_MODE}}{{PORTS}}{{EXTRA_HOSTS}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf:/etc/traefik/conf:ro
      - ./certs:/etc/traefik/certs
      - ./logs:/etc/traefik/logs
      - {{SITES_DIR}}:/etc/traefik/sites:ro{{NETWORKS}}

  dns:
    image: {{DNS_IMAGE}}
    container_name: {{DNS_CONTAINER}}
    restart: unless-stopped
    ports:
      - "127.0.0.1:53:53/udp"
    environment:
      - HTTP_USER={{DNS_HTTP_USER}}
      - HTTP_PASS={{DNS_HTTP_PASS}}
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    logging:
      driver: none{{HOST_RELAY}}

networks:
  traefik:
    name: {{NETWORK}}
    external: true
`

// generateRandomString generates a cryptographically random hex string of the
// specified length. Returns an error if the system's random source is unavailable
// so the caller can fail the specific operation without crashing the process.
func generateRandomString(length int) (string, error) {
	b := make([]byte, length/2+1)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("crypto/rand unavailable: %w", err)
	}
	return hex.EncodeToString(b)[:length], nil
}

// DockerComposeTemplate returns the docker-compose template with all variables substituted.
// dnsUser and dnsPass are the dnsmasq HTTP credentials; they must be loaded or
// generated by the caller (see loadOrGenerateDNSCredentials) to avoid rotation on
// every call.
// Credential values are YAML-single-quote-escaped so that any special characters
// in future credential formats cannot break the YAML structure.
//
// On Linux, Traefik uses network_mode: host to access localhost services directly.
// This allows 'srv proxy' to work with services bound to 127.0.0.1 without code changes.
// The custom Docker network is still used for container-to-container communication
// (containers connect to it and publish ports that Traefik can reach via localhost).
func DockerComposeTemplate(networkName, sitesDir, dnsUser, dnsPass string) string {
	// On Linux, use host networking to access localhost services directly
	// On Mac/Windows, Docker Desktop provides host.docker.internal automatically
	networkMode := ""
	ports := `
    ports:
      - "80:80"
      - "443:443"
      - "88:88"
      - "8080:8080"`
	extraHosts := ""
	networks := `
    networks:
      - traefik`
	hostRelay := ""

	if runtime.GOOS == "linux" {
		// Use host network mode on Linux - this gives Traefik access to localhost
		// Traefik can still proxy to Docker containers via their published ports on localhost
		networkMode = `
    network_mode: host`
		// Host mode doesn't need port mappings (Traefik binds directly to host ports)
		ports = ""
		// Host mode can't use custom networks, but Traefik can reach containers via Docker API
		networks = ""
		// No need for extra_hosts with host mode
		extraHosts = ""
	}

	r := strings.NewReplacer(
		"{{TRAEFIK_IMAGE}}", docker.ImageTraefik,
		"{{DNS_IMAGE}}", docker.ImageDNS,
		"{{TRAEFIK_CONTAINER}}", docker.ContainerTraefik,
		"{{DNS_CONTAINER}}", docker.ContainerDNS,
		"{{NETWORK_MODE}}", networkMode,
		"{{PORTS}}", ports,
		"{{EXTRA_HOSTS}}", extraHosts,
		"{{NETWORKS}}", networks,
		"{{HOST_RELAY}}", hostRelay,
		"{{NETWORK}}", networkName,
		"{{SITES_DIR}}", sitesDir,
		// Single-quote the credential values so YAML-special chars are safe.
		// Single quotes in the value itself are escaped as '' per YAML spec.
		"{{DNS_HTTP_USER}}", yamlSingleQuote(dnsUser),
		"{{DNS_HTTP_PASS}}", yamlSingleQuote(dnsPass),
	)
	return r.Replace(dockerComposeTemplate)
}

// yamlSingleQuote wraps s in YAML single quotes, escaping any literal single
// quotes inside the value by doubling them per the YAML 1.2 spec.
func yamlSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// readEnvFile reads the env.traefik file and returns its key/value pairs.
// Returns an empty map if the file does not exist.
func readEnvFile(path string) map[string]string {
	f, err := os.Open(path)
	if err != nil {
		return map[string]string{}
	}
	defer func() { _ = f.Close() }()
	parsed, err := envparse.Parse(f)
	if err != nil {
		return map[string]string{}
	}
	return parsed
}

// writeEnvFile persists a key/value map to path as a .env file atomically
// with 0600 permissions so credentials are not world-readable.
func writeEnvFile(path string, envMap map[string]string) error {
	// Produce deterministic output by sorting keys.
	keys := make([]string, 0, len(envMap))
	for k := range envMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var content strings.Builder
	for _, k := range keys {
		fmt.Fprintf(&content, "%s=%s\n", k, envMap[k])
	}

	// Write atomically so a crash mid-write never produces a partial file.
	tmp := path + constants.ExtTmp
	if err := os.WriteFile(tmp, []byte(content.String()), constants.FilePermACME); err != nil {
		return fmt.Errorf("failed to write env file: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("failed to install env file: %w", err)
	}
	return nil
}

// loadOrGenerateDNSCredentials reads DNS_HTTP_USER and DNS_HTTP_PASS from the
// env.traefik file. If either value is missing it generates fresh credentials,
// persists them alongside any existing keys, and returns the values.
func loadOrGenerateDNSCredentials(envPath string) (user, pass string, err error) {
	envMap := readEnvFile(envPath)

	user = envMap[constants.EnvDNSHTTPUser]
	pass = envMap[constants.EnvDNSHTTPPass]

	if user != "" && pass != "" {
		return user, pass, nil
	}

	// Generate missing values.
	if user == "" {
		user, err = generateRandomString(constants.DNSUserLength)
		if err != nil {
			return "", "", fmt.Errorf("failed to generate DNS user: %w", err)
		}
	}
	if pass == "" {
		pass, err = generateRandomString(constants.DNSPassLength)
		if err != nil {
			return "", "", fmt.Errorf("failed to generate DNS password: %w", err)
		}
	}

	// Persist all keys including the newly generated credentials.
	envMap[constants.EnvDNSHTTPUser] = user
	envMap[constants.EnvDNSHTTPPass] = pass

	if writeErr := writeEnvFile(envPath, envMap); writeErr != nil {
		return "", "", fmt.Errorf("failed to persist DNS credentials: %w", writeErr)
	}

	return user, pass, nil
}

// DnsmasqConf is the initial dnsmasq configuration (no domains).
// Domains are added dynamically via UpdateDnsmasqConfig().
const DnsmasqConf = `# Local domains managed by srv
# Do not edit manually - changes will be overwritten

# No local domains registered

# Forward all other queries to upstream DNS
server=8.8.8.8
server=8.8.4.4

# Don't read /etc/resolv.conf
no-resolv
`

// EnsureConfig ensures all Traefik configuration files exist.
// If traefik.yml exists, it merges user customizations with the template.
func EnsureConfig(email string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	// Create directories
	dirs := []string{
		cfg.TraefikDir,
		cfg.TraefikConfDir(),
		filepath.Join(cfg.TraefikDir, constants.CertsSubdir),
		filepath.Join(cfg.TraefikDir, constants.LogsSubdir),
		cfg.SitesDir,
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, constants.DirPermDefault); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	// Write or merge traefik.yml
	traefikPath := filepath.Join(cfg.TraefikConfDir(), "traefik.yml")
	if err := writeOrMergeTraefikYML(traefikPath, cfg.NetworkName, email); err != nil {
		return err
	}

	// Write traefik-dynamic.yml
	dynamicPath := filepath.Join(cfg.TraefikConfDir(), "traefik-dynamic.yml")
	if err := os.WriteFile(dynamicPath, []byte(TraefikDynamicYML), constants.FilePermDefault); err != nil {
		return fmt.Errorf("failed to write traefik-dynamic.yml: %w", err)
	}

	// Load or generate DNS credentials once; they are persisted to env.traefik so
	// subsequent calls to EnsureConfig reuse the same values instead of rotating them.
	dnsUser, dnsPass, err := loadOrGenerateDNSCredentials(cfg.EnvTraefikPath())
	if err != nil {
		return err
	}

	// Write docker-compose.yml
	composeYML := DockerComposeTemplate(cfg.NetworkName, cfg.SitesDir, dnsUser, dnsPass)
	composePath := cfg.TraefikComposePath()
	if err := os.WriteFile(composePath, []byte(composeYML), constants.FilePermDefault); err != nil {
		return fmt.Errorf("failed to write docker-compose.yml: %w", err)
	}

	// Write dnsmasq.conf — preserve registered domains on re-init.
	// On first run the file does not exist, so write the blank template.
	// On subsequent runs call UpdateDnsmasqConfig so existing domain
	// entries are regenerated from local-domains.txt rather than wiped.
	dnsmasqPath := filepath.Join(cfg.TraefikDir, constants.DnsmasqConfFile)
	if _, statErr := os.Stat(dnsmasqPath); os.IsNotExist(statErr) {
		if err := os.WriteFile(dnsmasqPath, []byte(DnsmasqConf), constants.FilePermDefault); err != nil {
			return fmt.Errorf("failed to write dnsmasq.conf: %w", err)
		}
	} else {
		if err := UpdateDnsmasqConfig(); err != nil {
			return fmt.Errorf("failed to refresh dnsmasq.conf: %w", err)
		}
	}

	// Create acme.json with proper permissions
	acmePath := filepath.Join(cfg.TraefikDir, constants.CertsSubdir, constants.ACMEJSONFile)
	if _, err := os.Stat(acmePath); os.IsNotExist(err) {
		if err := os.WriteFile(acmePath, []byte("{}"), constants.FilePermACME); err != nil {
			return fmt.Errorf("failed to create acme.json: %w", err)
		}
	}

	return nil
}

// writeOrMergeTraefikYML writes the traefik.yml file, merging with existing config if present.
// User-customizable sections (api, log, accessLog, metrics, tracing) are preserved.
// Managed sections (providers, certificatesResolvers) are always updated.
// For entryPoints, user-added entries are preserved but web/websecure are ensured.
func writeOrMergeTraefikYML(path, networkName, email string) error {
	// Prepare the template with substitutions
	templateYML := strings.ReplaceAll(TraefikYML, "{{NETWORK}}", networkName)
	templateYML = strings.ReplaceAll(templateYML, "{{EMAIL}}", email)

	// Check if file exists
	existingData, err := os.ReadFile(path)
	if err != nil {
		// File doesn't exist, write fresh
		if os.IsNotExist(err) {
			return os.WriteFile(path, []byte(templateYML), constants.FilePermDefault)
		}
		return fmt.Errorf("failed to read existing traefik.yml: %w", err)
	}

	// Parse existing config
	var existing map[string]any
	if err := yaml.Unmarshal(existingData, &existing); err != nil {
		// If parsing fails, overwrite with fresh config
		return os.WriteFile(path, []byte(templateYML), constants.FilePermDefault)
	}

	// Parse template config
	var template map[string]any
	if err := yaml.Unmarshal([]byte(templateYML), &template); err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	// Merge configs
	merged := mergeTraefikConfigs(existing, template)

	// Marshal back to YAML
	output, err := yaml.Marshal(merged)
	if err != nil {
		return fmt.Errorf("failed to marshal merged config: %w", err)
	}

	return os.WriteFile(path, output, constants.FilePermDefault)
}

// mergeTraefikConfigs merges existing config with template.
// - User sections (api, log, accessLog, metrics, tracing) are preserved from existing
// - Managed sections (providers, certificatesResolvers) are taken from template
// - entryPoints are merged: user additions preserved, web/websecure ensured from template
func mergeTraefikConfigs(existing, template map[string]any) map[string]any {
	result := make(map[string]any)

	// User-customizable sections - preserve from existing, fall back to template
	userSections := []string{"api", "log", "accessLog", "metrics", "tracing"}
	for _, section := range userSections {
		if val, ok := existing[section]; ok {
			result[section] = val
		} else if val, ok := template[section]; ok {
			result[section] = val
		}
	}

	// Managed sections - always use template
	managedSections := []string{"providers", "certificatesResolvers"}
	for _, section := range managedSections {
		if val, ok := template[section]; ok {
			result[section] = val
		}
	}

	// entryPoints - merge: preserve user additions, ensure web/websecure from template
	result["entryPoints"] = mergeEntryPoints(existing, template)

	return result
}

// mergeEntryPoints merges entryPoints configs.
// Preserves user-added entrypoints, ensures web/websecure/internal exist from template.
func mergeEntryPoints(existing, template map[string]any) map[string]any {
	result := make(map[string]any)

	// Start with existing entryPoints (preserves user additions)
	if existingEP, ok := existing["entryPoints"].(map[string]any); ok {
		maps.Copy(result, existingEP)
	}

	// Ensure the srv-managed entrypoints from the template are present.
	if templateEP, ok := template["entryPoints"].(map[string]any); ok {
		for _, name := range []string{"web", "websecure", constants.EntryPointInternal} {
			if v, ok := templateEP[name]; ok {
				result[name] = v
			}
		}
	}

	return result
}

// GetEmail returns the stored Let's Encrypt email or prompts for one.
func GetEmail(prompt bool) (string, error) {
	cfg, err := config.Load()
	if err != nil {
		return "", err
	}

	// Check for existing email using envparse for proper .env file parsing
	envPath := cfg.EnvTraefikPath()
	if file, err := os.Open(envPath); err == nil {
		defer func() { _ = file.Close() }()
		envMap, err := envparse.Parse(file)
		if err == nil {
			if email, ok := envMap[constants.EnvACMEEmail]; ok && email != "" {
				return email, nil
			}
		}
	}

	if !prompt {
		return "", fmt.Errorf("no email configured. Run: srv install")
	}

	// Prompt for email
	var email string
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("Let's Encrypt Email").
				Description("Used for SSL certificate notifications").
				Placeholder("you@example.com").
				Value(&email).
				Validate(func(s string) error {
					if !strings.Contains(s, "@") || !strings.Contains(s, ".") || strings.Index(s, "@") > strings.LastIndex(s, ".") {
						return fmt.Errorf("please enter a valid email address")
					}
					return nil
				}),
		),
	)

	if err := form.Run(); err != nil {
		return "", err
	}

	// Save email
	if err := SaveEmail(email); err != nil {
		return "", err
	}

	return email, nil
}

// SaveEmail saves the Let's Encrypt email to env.traefik, preserving any other
// keys already present (e.g. DNS_HTTP_USER / DNS_HTTP_PASS).
func SaveEmail(email string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	envPath := cfg.EnvTraefikPath()
	envMap := readEnvFile(envPath)
	envMap[constants.EnvACMEEmail] = email
	return writeEnvFile(envPath, envMap)
}

// IsRunning checks if Traefik container is running.
func IsRunning() bool {
	return docker.IsContainerRunning(docker.ContainerTraefik)
}

// DashboardURL returns the Traefik dashboard URL (plain HTTP, local port).
func DashboardURL() string {
	return fmt.Sprintf("%s%s:%d/dashboard/", constants.SchemeHTTPPrefix, constants.LocalhostIP, constants.PortDashboard)
}

// DashboardLocalURL returns the HTTPS dashboard URL via the traefik.local proxy.
func DashboardLocalURL() string {
	return fmt.Sprintf("https://%s/dashboard/", constants.TraefikDashboardDomain)
}

// SetupDashboardProxy creates (or refreshes) a local HTTPS proxy for the Traefik
// dashboard at traefik.local, including a mkcert SSL certificate and DNS registration.
// It is idempotent: calling it a second time renews the cert if needed but does not
// fail if the proxy config already exists.
func SetupDashboardProxy() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	domain := constants.TraefikDashboardDomain
	name := constants.TraefikDashboardProxyName
	proxySiteName := "_proxy-" + name

	// Generate (or renew) the mkcert certificate.
	if _, err := EnsureLocalCert(proxySiteName, []string{domain}, false); err != nil {
		return fmt.Errorf("failed to generate certificate for %s: %w", domain, err)
	}

	// Register domain with the local dnsmasq DNS server.
	if err := RegisterLocalDomain(domain, false); err != nil {
		return fmt.Errorf("failed to register DNS for %s: %w", domain, err)
	}

	// Write the Traefik router + service YAML config.
	// Routes traefik.local → http://127.0.0.1:8080 (the dashboard port).
	if err := writeDashboardProxyConfig(cfg, name, domain); err != nil {
		return err
	}

	// Regenerate traefik-dynamic.yml so the new cert is picked up.
	if err := UpdateDynamicConfig(); err != nil {
		return fmt.Errorf("failed to update dynamic config: %w", err)
	}

	return nil
}

// writeDashboardProxyConfig writes the Traefik router/service YAML for the
// dashboard proxy to the conf directory.
func writeDashboardProxyConfig(cfg *config.Config, name, domain string) error {
	type Server struct {
		URL string `yaml:"url"`
	}
	type LoadBalancer struct {
		Servers []Server `yaml:"servers"`
	}
	type Service struct {
		LoadBalancer LoadBalancer `yaml:"loadBalancer"`
	}
	type Router struct {
		Rule        string    `yaml:"rule"`
		EntryPoints []string  `yaml:"entryPoints"`
		Service     string    `yaml:"service"`
		TLS         *struct{} `yaml:"tls,omitempty"`
	}
	type HTTP struct {
		Routers  map[string]Router  `yaml:"routers"`
		Services map[string]Service `yaml:"services"`
	}
	type ProxyConfig struct {
		HTTP HTTP `yaml:"http"`
	}

	routerName := constants.ProxyConfigPrefix + name
	targetURL := fmt.Sprintf("%s%s:%d", constants.SchemeHTTPPrefix, constants.LocalhostAlias, constants.PortDashboard)

	proxyConfig := ProxyConfig{
		HTTP: HTTP{
			Routers: map[string]Router{
				routerName: {
					Rule:        fmt.Sprintf("Host(`%s`)", domain),
					EntryPoints: []string{constants.EntryPointWebsecure},
					Service:     routerName,
					TLS:         &struct{}{},
				},
			},
			Services: map[string]Service{
				routerName: {
					LoadBalancer: LoadBalancer{
						Servers: []Server{{URL: targetURL}},
					},
				},
			},
		},
	}

	data, err := yaml.Marshal(&proxyConfig)
	if err != nil {
		return fmt.Errorf("failed to marshal dashboard proxy config: %w", err)
	}

	content := fmt.Sprintf(
		"# Proxy configuration for %s - generated by srv\n# Domain: %s\n%s",
		name, domain, data,
	)

	proxyFile := filepath.Join(cfg.TraefikConfDir(), constants.ProxyConfigPrefix+name+constants.ExtYAML)
	return os.WriteFile(proxyFile, []byte(content), constants.FilePermDefault)
}

// IsDNSRunning checks if the DNS container is running.
func IsDNSRunning() bool {
	return docker.IsContainerRunning(docker.ContainerDNS)
}

// CheckPortAvailable checks if a port is available for binding.
func CheckPortAvailable(port int) bool {
	portStr := fmt.Sprintf("%d", port)
	inUse, err := shell.CheckPort(portStr)
	if err != nil {
		return true // Assume available if we can't check
	}
	return !inUse
}

// PortConflict describes a port that is already in use by a non-srv process.
type PortConflict struct {
	Port    int
	Name    string // human-readable name, e.g. "HTTP"
	Process string // process name if identifiable, else ""
}

// StopHint returns an actionable command string to stop the conflicting process,
// or a generic message if the process could not be identified.
func (c PortConflict) StopHint() string {
	switch c.Process {
	case "nginx", "lighttpd", "caddy", "apache2", "httpd":
		return fmt.Sprintf("sudo systemctl stop %s", c.Process)
	default:
		if c.Process != "" {
			return fmt.Sprintf("sudo systemctl stop %s", c.Process)
		}
		return fmt.Sprintf("identify and stop the process using port %d (try: sudo ss -tlnp | grep :%d)", c.Port, c.Port)
	}
}

// CanAutoFix reports whether srv knows how to fix this conflict automatically.
func (c PortConflict) CanAutoFix() bool {
	switch c.Process {
	case "nginx", "apache2", "httpd", "lighttpd", "caddy":
		return true
	}
	return false
}

// AutoFix attempts to automatically resolve the port conflict.
func (c PortConflict) AutoFix() error {
	switch c.Process {
	case "nginx", "lighttpd", "caddy", "apache2", "httpd":
		return shell.SudoRun("systemctl", "stop", c.Process)
	default:
		return fmt.Errorf("no automatic fix available for process %q", c.Process)
	}
}

// CheckPortConflicts checks whether any of the ports srv requires are occupied
// by a non-srv process. It skips ports already owned by srv containers.
// Only ports 80, 443, and 53 are checked; port 8080 (dashboard) is advisory only.
//
// Port 53 is checked on 127.0.0.1 specifically, because the dnsmasq container
// binds "127.0.0.1:53:53/udp" — not 0.0.0.0:53. systemd-resolved's stub
// listener on 127.0.0.53:53 does not conflict with this binding and is not
// reported as a conflict.
func CheckPortConflicts() []PortConflict {
	type check struct {
		port      int
		bindAddr  string // specific bind address to check; "" means 0.0.0.0
		name      string
		ownedByFn func() bool
	}

	checks := []check{
		{constants.PortHTTP, "", constants.PortNameHTTP, IsRunning},
		{constants.PortHTTPS, "", constants.PortNameHTTPS, IsRunning},
		// DNS binds on 127.0.0.1 only — check that address, not 0.0.0.0.
		{constants.PortDNS, constants.LocalhostIP, constants.PortNameDNS, IsDNSRunning},
	}

	var conflicts []PortConflict
	for _, c := range checks {
		portStr := fmt.Sprintf("%d", c.port)
		inUse, _ := shell.CheckPortOnAddr(c.bindAddr, portStr)
		if !inUse {
			continue // port is free at the relevant address
		}
		if c.ownedByFn() {
			continue // port is ours — no conflict
		}
		process := shell.IdentifyPortProcess(portStr)
		conflicts = append(conflicts, PortConflict{
			Port:    c.port,
			Name:    c.name,
			Process: process,
		})
	}
	return conflicts
}

// RestartTraefik restarts the Traefik container.
func RestartTraefik() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	return docker.Compose(cfg.TraefikDir, "restart")
}

// RecreateTraefik recreates Traefik containers with the latest image.
func RecreateTraefik() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	return docker.Compose(cfg.TraefikDir, "up", "-d", "--force-recreate")
}

// Reset removes the entire srv configuration directory for a fresh start.
func Reset() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	// Stop Traefik containers first if running (ignore errors - best effort cleanup)
	if IsRunning() || IsDNSRunning() {
		// Intentionally ignoring error: we're resetting anyway, compose down may fail
		// if containers are in an inconsistent state
		_ = docker.Compose(cfg.TraefikDir, "down")
	}

	// Remove the config directory
	if err := os.RemoveAll(cfg.Root); err != nil {
		return fmt.Errorf("failed to remove config directory: %w", err)
	}

	// Reset the config cache so it gets reloaded
	config.ResetCache()

	return nil
}
