// Package cmd — site_add_detect.go contains the project-type detection
// flow for `srv add`: probing the filesystem for compose/PHP/Node/Ruby/etc.,
// honouring the --type override, and producing a one-liner detection summary.
package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/stubbedev/srv/internal/constants"
	"github.com/stubbedev/srv/internal/site"
)

// validateSiteSetup validates the path and discovers compose / language
// project. Detection order (when --type is not specified):
//  1. docker-compose.yml present → compose site
//  2. composer.json or *.php present → ERROR pointing at `srv scaffold php`
//     (srv no longer manages PHP runtimes; user provides a Dockerfile or
//     compose, optionally generated by the scaffold command)
//  3. package.json / deno.json   → Node.js / Bun / Deno site
//  4. Gemfile present            → Ruby site
//  5. requirements.txt / pyproject.toml / Pipfile → Python site
//  6. Dockerfile present         → Dockerfile site
//  7. otherwise                  → static site
func validateSiteSetup(pathArg string) (*siteSetup, error) {
	sitePath, err := site.ResolvePath(pathArg)
	if err != nil {
		return nil, fmt.Errorf("invalid path: %w", err)
	}

	if _, err := os.Stat(sitePath); err != nil {
		return nil, fmt.Errorf("path does not exist: %s", sitePath)
	}

	setup := &siteSetup{
		sitePath: sitePath,
		port:     addFlags.port,
	}

	// --type override: skip auto-detection and set type directly.
	if addFlags.typeOverride != "" {
		return applyTypeOverride(setup, sitePath, addFlags.typeOverride)
	}

	// 1. Try to find a compose file.
	composePath, err := site.FindComposeFile(sitePath)
	if err != nil && !site.IsNotFoundError(err) {
		return nil, fmt.Errorf("could not check for docker-compose file: %w", err)
	}
	if err == nil {
		setup.composePath = composePath
		return setup, nil
	}

	// 2. PHP project (composer.json / .php files) without a Dockerfile or
	//    docker-compose.yml: srv no longer owns the PHP runtime. Refuse and
	//    point at the scaffold + --type escape hatches.
	if hasPHPProject(sitePath) {
		return nil, fmt.Errorf(
			"this looks like a PHP project (composer.json or .php files found) but no Dockerfile or docker-compose.yml is present.\n" +
				"  srv no longer manages PHP runtimes directly.\n" +
				"  options:\n" +
				"    1. `srv scaffold php` to generate a Dockerfile + docker-compose.yml in the project\n" +
				"    2. write your own Dockerfile / docker-compose.yml and re-run `srv add`\n" +
				"    3. pass `--type static` to serve only the static files in the project")
	}

	// 3. Try Node.js / Bun / Deno detection.
	nodeInfo, err := site.DetectNodeSite(sitePath)
	if err != nil {
		return nil, fmt.Errorf("could not check for Node.js project: %w", err)
	}
	if nodeInfo != nil {
		setup.isNode = true
		setup.nodeInfo = nodeInfo
		return setup, nil
	}

	// 5. Try Ruby detection (Gemfile).
	rubyInfo, err := site.DetectRubySite(sitePath)
	if err != nil {
		return nil, fmt.Errorf("could not check for Ruby project: %w", err)
	}
	if rubyInfo != nil {
		setup.isRuby = true
		setup.rubyInfo = rubyInfo
		return setup, nil
	}

	// 6. Try Python detection.
	pythonInfo, err := site.DetectPythonSite(sitePath)
	if err != nil {
		return nil, fmt.Errorf("could not check for Python project: %w", err)
	}
	if pythonInfo != nil {
		setup.isPython = true
		setup.pythonInfo = pythonInfo
		return setup, nil
	}

	// 7. Try bare Dockerfile detection.
	dockerfileInfo, err := site.DetectDockerfileSite(sitePath)
	if err != nil {
		return nil, fmt.Errorf("could not check for Dockerfile: %w", err)
	}
	if dockerfileInfo != nil {
		setup.isDockerfile = true
		setup.dockerfileInfo = dockerfileInfo
		return setup, nil
	}

	// 8. Fall back to static site.
	setup.isStatic = true
	return setup, nil
}

// applyTypeOverride forces a specific site type, running detection only for that type.
func applyTypeOverride(setup *siteSetup, sitePath, typeStr string) (*siteSetup, error) {
	switch strings.ToLower(typeStr) {
	case "node":
		nodeInfo, err := site.DetectNodeSite(sitePath)
		if err != nil || nodeInfo == nil {
			nodeInfo = site.NodeDefaults()
		}
		setup.isNode = true
		setup.nodeInfo = nodeInfo
	case "ruby":
		rubyInfo, err := site.DetectRubySite(sitePath)
		if err != nil || rubyInfo == nil {
			rubyInfo = &site.RubySiteInfo{
				RubyVersion: constants.RubyVersionLatest,
				Framework:   constants.RubyFrameworkGeneric,
				Port:        constants.RubyDefaultPort,
				StartCmd:    "sh -c 'bundle install && bundle exec ruby app.rb'",
			}
		}
		setup.isRuby = true
		setup.rubyInfo = rubyInfo
	case "python":
		pythonInfo, err := site.DetectPythonSite(sitePath)
		if err != nil || pythonInfo == nil {
			pythonInfo = &site.PythonSiteInfo{
				PythonVersion: constants.PythonVersionLatest,
				Framework:     constants.PythonFrameworkGeneric,
				Port:          constants.PythonDefaultPort,
				StartCmd:      "sh -c 'pip install -r requirements.txt && python app.py'",
			}
		}
		setup.isPython = true
		setup.pythonInfo = pythonInfo
	case "dockerfile":
		dockerfileInfo, err := site.DetectDockerfileSite(sitePath)
		if err != nil || dockerfileInfo == nil {
			dockerfileInfo = &site.DockerfileSiteInfo{Port: constants.DockerfileDefaultPort}
		}
		setup.isDockerfile = true
		setup.dockerfileInfo = dockerfileInfo
	case "static":
		setup.isStatic = true
	case "compose":
		composePath, err := site.FindComposeFile(sitePath)
		if err != nil {
			return nil, fmt.Errorf("no docker-compose.yml found (required for --type compose)")
		}
		setup.composePath = composePath
	default:
		return nil, fmt.Errorf("unknown site type %q — valid types: node, ruby, python, dockerfile, static, compose", typeStr)
	}
	return setup, nil
}

// hasPHPProject reports whether dir looks like a PHP project that srv would
// previously have managed (composer.json or a top-level .php / .phtml file).
// Used to surface a hard error when there's no Dockerfile/compose to drive
// the runtime — srv no longer manages PHP runtimes directly.
func hasPHPProject(dir string) bool {
	if _, err := os.Stat(filepath.Join(dir, "composer.json")); err == nil {
		return true
	}
	if hasRawPHP, _ := site.DetectRawPHPSite(dir); hasRawPHP {
		return true
	}
	return false
}

// detectionSummary returns a human-readable summary of what was detected for a site.
func detectionSummary(setup *siteSetup) string {
	switch {
	case setup.composePath != "":
		return "docker-compose project"
	case setup.isNode && setup.nodeInfo != nil:
		info := setup.nodeInfo
		runtime := info.Runtime
		if info.PackageManager != info.Runtime && info.PackageManager != constants.NodePMDeno {
			runtime += " / " + info.PackageManager
		}
		fw := info.Framework
		ver := info.NodeVersion
		if fw != "generic" {
			return fmt.Sprintf("%s (%s %s)", fw, runtime, ver)
		}
		return fmt.Sprintf("%s %s", runtime, ver)
	case setup.isRuby && setup.rubyInfo != nil:
		info := setup.rubyInfo
		if info.Framework != constants.RubyFrameworkGeneric {
			return fmt.Sprintf("%s (ruby %s)", info.Framework, info.RubyVersion)
		}
		return fmt.Sprintf("ruby %s", info.RubyVersion)
	case setup.isPython && setup.pythonInfo != nil:
		info := setup.pythonInfo
		if info.Framework != constants.PythonFrameworkGeneric {
			return fmt.Sprintf("%s (python %s)", info.Framework, info.PythonVersion)
		}
		return fmt.Sprintf("python %s", info.PythonVersion)
	case setup.isDockerfile && setup.dockerfileInfo != nil:
		return fmt.Sprintf("Dockerfile (port %d)", setup.dockerfileInfo.Port)
	case setup.isStatic:
		return "static site"
	default:
		return "unknown"
	}
}
