// Package site — dockerfile.go handles the SiteTypeDockerfile path: project
// has a Dockerfile in the root, srv generates a thin docker-compose.yml that
// builds from it and attaches the Traefik routing labels.
package site

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
)

// DockerfileSiteInfo holds detected configuration for a project with a bare Dockerfile.
type DockerfileSiteInfo struct {
	Port int // Port from EXPOSE directive (or default)
}

// DetectDockerfileSite checks whether dir contains a bare Dockerfile (no docker-compose.yml).
// Returns nil if no Dockerfile is found.
func DetectDockerfileSite(dir string) (*DockerfileSiteInfo, error) {
	dockerfilePath := filepath.Join(dir, constants.DockerfileFile)
	f, err := os.Open(dockerfilePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading Dockerfile: %w", err)
	}
	defer func() { _ = f.Close() }()

	port := parseDockerfileExposePort(f)
	if port == 0 {
		port = constants.DockerfileDefaultPort
	}
	return &DockerfileSiteInfo{Port: port}, nil
}

// parseDockerfileExposePort scans a Dockerfile for the first EXPOSE directive
// and returns the port. Returns 0 if no EXPOSE is found.
func parseDockerfileExposePort(f io.Reader) int {
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(strings.ToUpper(line), "EXPOSE") {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) < 2 {
			continue
		}
		portStr := strings.SplitN(parts[1], "/", 2)[0]
		if p, err := strconv.Atoi(portStr); err == nil && p > 0 {
			return p
		}
	}
	return 0
}

// WriteDockerfileSiteConfig writes the per-site docker-compose.yml that
// builds from the project's Dockerfile and attaches Traefik labels.
func WriteDockerfileSiteConfig(name string, meta SiteMetadata, info *DockerfileSiteInfo, force bool) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	siteDir := SiteConfigDir(cfg, name)
	if err := os.MkdirAll(siteDir, constants.DirPermDefault); err != nil {
		return fmt.Errorf("failed to create site config directory: %w", err)
	}

	containerName := "srv-" + name + "-app"
	labels := buildTraefikLabels(name, meta.Domains, meta.IsLocal, meta.Wildcard, info.Port)
	if HasListener(meta.Listeners, constants.ListenerInternal) {
		addInternalListenerLabels(labels, name, meta.Domains, meta.Wildcard)
	}
	StampSrvLabels(labels, name, string(meta.Type))

	cf := composeFile{
		Name: constants.ComposeProjectFor(name),
		Services: map[string]composeService{
			"app": {
				ContainerName: containerName,
				Build: &composeBuild{
					Context:    meta.ProjectPath,
					Dockerfile: constants.DockerfileFile,
				},
				Labels:      labels,
				Networks:    []string{constants.TraefikSubdir},
				Restart:     constants.RestartUnlessStopped,
				HealthCheck: makeComposeHealthCheck(info.Port),
			},
		},
		Networks: map[string]composeNetwork{
			constants.TraefikSubdir: {Name: meta.NetworkName, External: true},
		},
	}

	data, err := yaml.Marshal(&cf)
	if err != nil {
		return fmt.Errorf("failed to marshal compose config: %w", err)
	}

	header := fmt.Sprintf(`# Generated by srv - dockerfile site
# Project: %s
#
# This file is yours to edit. Changes take effect on next restart.
# Run "srv site restart %s --build" to rebuild the image after Dockerfile changes.
#
# The image is built from: %s/Dockerfile

`, meta.ProjectPath, name, meta.ProjectPath)
	content := header + string(data)

	composePath := SiteComposePath(cfg, name)
	return writeFile(composePath, []byte(content), force)
}
