// Package site — dockerfile.go handles the SiteTypeDockerfile path: project
// has a Dockerfile in the root, srv generates a thin docker-compose.yml that
// builds from it and attaches the Traefik routing labels.
package site

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
)

// DockerfileSiteInfo holds detected configuration for a project with a bare Dockerfile.
type DockerfileSiteInfo struct {
	Port int // Port from EXPOSE directive (or default)
}

// DetectDockerfileSite checks whether dir contains a bare Dockerfile (no docker-compose.yml).
// Returns nil if no Dockerfile is found.
func DetectDockerfileSite(dir string) (*DockerfileSiteInfo, error) {
	dockerfilePath := filepath.Join(dir, constants.DockerfileFile)
	f, err := os.Open(dockerfilePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading Dockerfile: %w", err)
	}
	defer func() { _ = f.Close() }()

	port, err := parseDockerfileExposePort(f)
	if err != nil {
		return nil, err
	}
	if port == 0 {
		port = constants.DockerfileDefaultPort
	}
	return &DockerfileSiteInfo{Port: port}, nil
}

// parseDockerfileExposePort scans a Dockerfile for the first EXPOSE directive
// and returns the port. Returns 0 with a nil error if no EXPOSE is found; a
// non-nil error means the Dockerfile could not be read in full, which must not
// silently downgrade the site to the default port.
func parseDockerfileExposePort(f io.Reader) (int, error) {
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(strings.ToUpper(line), "EXPOSE") {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) < 2 {
			continue
		}
		portStr, _, _ := strings.Cut(parts[1], "/")
		if p, err := strconv.Atoi(portStr); err == nil && p > 0 {
			return p, nil
		}
	}
	if err := scanner.Err(); err != nil {
		return 0, fmt.Errorf("scanning Dockerfile for EXPOSE: %w", err)
	}
	return 0, nil
}

// WriteDockerfileSiteConfig writes the per-site docker-compose.yml that
// builds from the project's Dockerfile and attaches Traefik labels.
func WriteDockerfileSiteConfig(name string, meta SiteMetadata, info *DockerfileSiteInfo, force bool) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	siteDir := SiteConfigDir(cfg, name)
	if err := os.MkdirAll(siteDir, constants.DirPermDefault); err != nil {
		return fmt.Errorf("failed to create site config directory: %w", err)
	}

	containerName := "srv-" + name + "-app"
	labels := buildTraefikLabels(name, meta.Domains, meta.IsLocal, meta.Wildcard, info.Port)
	if HasListener(meta.Listeners, constants.ListenerInternal) {
		addInternalListenerLabels(labels, name, meta.Domains, meta.Wildcard)
	}
	StampSrvLabels(labels, name, string(meta.Type))

	// Extra bind-mounts and networks from metadata are rendered so `srv
	// volume add` and `srv network attach` have an effect on dockerfile sites.
	vols := make([]composeVolume, 0, len(meta.Volumes))
	for _, v := range meta.Volumes {
		vols = append(vols, composeVolume{
			Type:     "bind",
			Source:   v.Source,
			Target:   v.Target,
			ReadOnly: v.ReadOnly,
		})
	}
	networks := append([]string{constants.TraefikSubdir}, meta.ExtraNetworks...)
	composeNetworks := map[string]composeNetwork{
		constants.TraefikSubdir: {Name: meta.NetworkName, External: true},
	}
	for _, n := range meta.ExtraNetworks {
		composeNetworks[n] = composeNetwork{Name: n, External: true}
	}

	cf := composeFile{
		Name: constants.ComposeProjectFor(name),
		Services: map[string]composeService{
			"app": {
				ContainerName: containerName,
				Build: &composeBuild{
					Context:    meta.ProjectPath,
					Dockerfile: constants.DockerfileFile,
				},
				Volumes:  vols,
				Labels:   labels,
				Networks: networks,
				Restart:  constants.RestartUnlessStopped,
			},
		},
		Networks: composeNetworks,
	}

	data, err := yaml.Marshal(&cf)
	if err != nil {
		return fmt.Errorf("failed to marshal compose config: %w", err)
	}

	header := fmt.Sprintf(`# Generated by srv - dockerfile site
# Project: %s
#
# This file is yours to edit. Changes take effect on next restart.
# Run "srv site restart %s --build" to rebuild the image after Dockerfile changes.
#
# The image is built from: %s/Dockerfile

`, meta.ProjectPath, name, meta.ProjectPath)
	content := header + string(data)

	composePath := SiteComposePath(cfg, name)
	return writeFile(composePath, []byte(content), force)
}
