// Package site handles site management operations.
package site

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
)

// =============================================================================
// Dockerfile Site Detection
// =============================================================================

// DockerfileSiteInfo holds detected configuration for a project with a bare Dockerfile.
type DockerfileSiteInfo struct {
	Port int // Port from EXPOSE directive (or default)
}

// DetectDockerfileSite checks whether dir contains a bare Dockerfile (no docker-compose.yml).
// Returns nil if no Dockerfile is found.
func DetectDockerfileSite(dir string) (*DockerfileSiteInfo, error) {
	dockerfilePath := filepath.Join(dir, constants.DockerfileFile)
	f, err := os.Open(dockerfilePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading Dockerfile: %w", err)
	}
	defer func() { _ = f.Close() }()

	port := parseDockerfileExposePort(f)
	if port == 0 {
		port = constants.DockerfileDefaultPort
	}

	return &DockerfileSiteInfo{Port: port}, nil
}

// parseDockerfileExposePort scans a Dockerfile for the first EXPOSE directive and returns the port.
func parseDockerfileExposePort(f io.Reader) int {
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(strings.ToUpper(line), "EXPOSE") {
			continue
		}
		// "EXPOSE 8080" or "EXPOSE 8080/tcp"
		parts := strings.Fields(line)
		if len(parts) < 2 {
			continue
		}
		portStr := strings.SplitN(parts[1], "/", 2)[0]
		if p, err := strconv.Atoi(portStr); err == nil && p > 0 {
			return p
		}
	}
	return 0
}

// =============================================================================
// Docker Compose generation (Dockerfile)
// =============================================================================

type dockerfileServiceConfig struct {
	ContainerName string            `yaml:"container_name"`
	Build         dockerfileBuild   `yaml:"build"`
	WorkingDir    string            `yaml:"working_dir,omitempty"`
	Labels        map[string]string `yaml:"labels,omitempty"`
	Networks      []string          `yaml:"networks"`
	Restart       string            `yaml:"restart"`
}

type dockerfileBuild struct {
	Context    string `yaml:"context"`
	Dockerfile string `yaml:"dockerfile"`
}

type dockerfileComposeConfig struct {
	Services map[string]dockerfileServiceConfig `yaml:"services"`
	Networks map[string]nodeNetworkConfig       `yaml:"networks"`
}

// WriteDockerfileSiteConfig generates and writes docker-compose.yml for a Dockerfile site.
// The compose file instructs Docker Compose to build from the project's Dockerfile.
func WriteDockerfileSiteConfig(name string, meta SiteMetadata, info *DockerfileSiteInfo, force bool) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	siteDir := SiteConfigDir(cfg, name)
	if err := os.MkdirAll(siteDir, constants.DirPermDefault); err != nil {
		return fmt.Errorf("failed to create site config directory: %w", err)
	}

	containerName := "srv-" + name + "-app"
	labels := buildAppTraefikLabels(name, meta.Domains, meta.IsLocal, meta.Wildcard, info.Port)
	if HasListener(meta.Listeners, constants.ListenerInternal) {
		addInternalListenerLabels(labels, name, meta.Domains, meta.Wildcard)
	}

	composeConfig := dockerfileComposeConfig{
		Services: map[string]dockerfileServiceConfig{
			"app": {
				ContainerName: containerName,
				Build: dockerfileBuild{
					Context:    meta.ProjectPath,
					Dockerfile: constants.DockerfileFile,
				},
				Labels:   labels,
				Networks: []string{constants.TraefikSubdir},
				Restart:  constants.RestartUnlessStopped,
			},
		},
		Networks: map[string]nodeNetworkConfig{
			constants.TraefikSubdir: {
				Name:     meta.NetworkName,
				External: true,
			},
		},
	}

	data, err := yaml.Marshal(&composeConfig)
	if err != nil {
		return fmt.Errorf("failed to marshal compose config: %w", err)
	}

	header := fmt.Sprintf(`# Generated by srv - dockerfile site
# Project: %s
#
# This file is yours to edit. Changes take effect on next restart.
# Run "srv site restart %s --build" to rebuild the image after Dockerfile changes.
#
# The image is built from: %s/Dockerfile

`, meta.ProjectPath, name, meta.ProjectPath)
	content := header + string(data)

	composePath := SiteComposePath(cfg, name)
	return writeFile(composePath, []byte(content), force)
}
