// Package site — php_render.go renders the per-site PHP artifacts that
// don't depend on the shared FPM pool: nginx.conf (with fastcgi_pass
// pointed at the pool container), the php.ini overrides, the per-pool
// php-fpm.conf, and the Dockerfile used to build the pool image. The
// PHPImageFingerprint that drives pool sharing is also defined here.
package site

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"

	"github.com/stubbedev/srv/internal/constants"
)

// =============================================================================
// Nginx config generation (PHP)
// =============================================================================

// generatePHPFPMConf generates an FPM pool override file. Local-only sites
// use `pm = ondemand` so idle sites consume zero workers; production sites
// (Let's Encrypt resolver) keep the dynamic default for steady throughput.
func generatePHPFPMConf(isLocal bool) string {
	pm := "dynamic"
	if isLocal {
		pm = "ondemand"
	}
	return fmt.Sprintf(`; Generated by srv — PHP-FPM pool override.
; Mounted at %s so it sorts after the base image's www.conf.

[www]
pm = %s
pm.max_children = 16
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
pm.process_idle_timeout = 10s
pm.max_requests = 500
`, constants.PHPFPMConfContainerPath, pm)
}

// generatePHPIni generates a php.ini with sensible development defaults.
// It is mounted into the container as a drop-in override file so it cannot
// conflict with the base image's own php.ini.
func generatePHPIni() string {
	return `; Generated by srv - PHP site configuration overrides
; This file is yours to edit. "srv site regenerate" will reset it.
; Tuned for local development — adjust values as needed.

[PHP]
memory_limit          = 2G
upload_max_filesize   = 2G
post_max_size         = 2G
max_execution_time    = 300
max_input_time        = 300
max_input_vars        = 10000
date.timezone         = UTC

; Uncomment to enable Xdebug step debugging:
;xdebug.mode          = debug
;xdebug.start_with_request = yes
;xdebug.client_host   = host.docker.internal
;xdebug.client_port   = 9003

[Session]
session.gc_maxlifetime = 86400
`
}

// generatePHPNginxConf generates an nginx configuration for a PHP site.
// limits, if non-nil, overrides default client_max_body_size and fastcgi_*_timeout
// directives. siteName + fpmHost together set the SCRIPT_FILENAME prefix and
// the upstream FPM container that lives in the shared pool.
func generatePHPNginxConf(info *PHPSiteInfo, limits *Limits, siteName, fpmHost string) string {
	// Determine the document root path inside the container. With the shared
	// FPM pool each site is mounted at /var/www/<sitename>, and both nginx
	// and FPM containers see the same path so SCRIPT_FILENAME resolves on
	// both ends.
	siteRoot := constants.PHPSiteDocRootRoot + "/" + siteName
	docRoot := siteRoot
	if info.DocumentRoot != "" {
		docRoot = siteRoot + "/" + info.DocumentRoot
	}

	// Determine entry point based on framework.
	entryPoint := "index.php"
	if info.Framework == constants.PHPFrameworkSymfony {
		// Older Symfony used app.php; check whether the web/ docroot is used
		// (a simple heuristic — if web/ then it's likely Symfony <4).
		if info.DocumentRoot == "web" {
			entryPoint = "app.php"
		}
	}

	// WordPress needs $args in its try_files.
	tryFilesArgs := "$query_string"
	if info.Framework == constants.PHPFrameworkWordPress {
		tryFilesArgs = "$args"
	}

	var sb strings.Builder
	sb.WriteString("# Generated by srv - PHP site nginx config\n")
	sb.WriteString("# This file is yours to edit. \"srv site regenerate\" will reset it.\n")
	sb.WriteString("#\n")
	sb.WriteString("# Uncomment to add a WebSocket proxy (e.g. Laravel Reverb on port 8080):\n")
	sb.WriteString("#\n")
	sb.WriteString("#   location /app {\n")
	sb.WriteString("#       proxy_pass http://php:8080;\n")
	sb.WriteString("#       proxy_http_version 1.1;\n")
	sb.WriteString("#       proxy_set_header Upgrade $http_upgrade;\n")
	sb.WriteString("#       proxy_set_header Connection \"upgrade\";\n")
	sb.WriteString("#       proxy_set_header Host $host;\n")
	sb.WriteString("#   }\n")
	sb.WriteString("\n")
	sb.WriteString("server {\n")
	sb.WriteString("    listen 80;\n")
	sb.WriteString("    server_name _;\n")
	fmt.Fprintf(&sb, "    root %s;\n", docRoot)
	fmt.Fprintf(&sb, "    index index.php index.phtml index.html;\n")
	sb.WriteString("\n")
	// Match php.ini upload_max_filesize / post_max_size so nginx doesn't
	// reject large requests before PHP even sees them.
	maxBody := "2G"
	if limits != nil && limits.MaxBody != "" {
		maxBody = limits.MaxBody
	}
	fmt.Fprintf(&sb, "    client_max_body_size %s;\n", maxBody)
	sb.WriteString("\n")

	// Gzip
	sb.WriteString("    # Gzip compression\n")
	sb.WriteString("    gzip on;\n")
	sb.WriteString("    gzip_vary on;\n")
	sb.WriteString("    gzip_min_length 1024;\n")
	sb.WriteString("    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml;\n")
	sb.WriteString("\n")

	// Security headers
	sb.WriteString("    # Security headers\n")
	sb.WriteString("    add_header X-Frame-Options \"SAMEORIGIN\" always;\n")
	sb.WriteString("    add_header X-Content-Type-Options \"nosniff\" always;\n")
	sb.WriteString("    add_header X-XSS-Protection \"1; mode=block\" always;\n")
	sb.WriteString("\n")

	// Deny dotfiles (must come before the PHP location block).
	sb.WriteString("    # Block access to hidden files (dotfiles)\n")
	sb.WriteString("    location ~ /\\. {\n")
	sb.WriteString("        deny all;\n")
	sb.WriteString("        return 404;\n")
	sb.WriteString("    }\n")
	sb.WriteString("\n")

	// Laravel: also deny .env explicitly.
	if info.Framework == constants.PHPFrameworkLaravel {
		sb.WriteString("    # Block access to .env files\n")
		sb.WriteString("    location ~ \\.env$ {\n")
		sb.WriteString("        deny all;\n")
		sb.WriteString("        return 404;\n")
		sb.WriteString("    }\n")
		sb.WriteString("\n")
	}

	// Block sensitive directories.
	sb.WriteString("    # Block access to common sensitive directories\n")
	sb.WriteString("    location ~* ^/(vendor|node_modules|\\.git|\\.svn)/ {\n")
	sb.WriteString("        deny all;\n")
	sb.WriteString("        return 404;\n")
	sb.WriteString("    }\n")
	sb.WriteString("\n")

	// Main location block.
	sb.WriteString("    # Route all requests through the PHP entry point\n")
	sb.WriteString("    location / {\n")
	fmt.Fprintf(&sb, "        try_files $uri $uri/ /%s?%s;\n", entryPoint, tryFilesArgs)
	sb.WriteString("    }\n")
	sb.WriteString("\n")

	// PHP/PHTML processing via FastCGI.
	sb.WriteString("    # PHP and PHTML processing via PHP-FPM\n")
	sb.WriteString("    location ~ \\.(php|phtml)$ {\n")
	fmt.Fprintf(&sb, "        fastcgi_pass %s:%d;\n", fpmHost, constants.PHPFPMPort)
	sb.WriteString("        fastcgi_index index.php;\n")
	sb.WriteString("        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;\n")
	sb.WriteString("        include fastcgi_params;\n")
	if limits != nil {
		if limits.ConnectTimeout != "" {
			fmt.Fprintf(&sb, "        fastcgi_connect_timeout %s;\n", limits.ConnectTimeout)
		}
		if limits.SendTimeout != "" {
			fmt.Fprintf(&sb, "        fastcgi_send_timeout %s;\n", limits.SendTimeout)
		}
		if limits.ReadTimeout != "" {
			fmt.Fprintf(&sb, "        fastcgi_read_timeout %s;\n", limits.ReadTimeout)
		}
	}
	sb.WriteString("    }\n")
	sb.WriteString("}\n")

	return sb.String()
}

// =============================================================================
// Dockerfile generation (PHP)
// =============================================================================

// ipeExtensions is the full list of PHP extensions supported by
// install-php-extensions (https://github.com/mlocati/docker-php-extension-installer).
// All dependency resolution (Alpine packages, PECL vs bundled, configure flags)
// is handled automatically by IPE at build time.
var ipeExtensions = []string{
	"amqp", "apcu", "apcu_bc", "ast",
	"bcmath", "bitset", "blackfire", "brotli", "bz2",
	"calendar", "cassandra", "cmark", "csv",
	"dba", "ddtrace", "decimal", "ds",
	"ecma_intl", "enchant", "ev", "event", "excimer", "exif",
	"ffi", "ftp",
	"gd", "gearman", "geoip", "geos", "geospatial", "gettext", "gmagick", "gmp", "gnupg", "grpc",
	"http",
	"igbinary", "imagick", "imap", "inotify", "intl", "ion", "ioncube_loader", "ip2location",
	"jsmin", "json_post", "jsonpath", "judy",
	"ldap", "luasandbox", "lz4", "lzf",
	"mailparse", "maxminddb", "mbstring", "mcrypt", "md4c", "memcache", "memcached", "memprof",
	"mongodb", "msgpack", "mysqli",
	"oauth", "oci8", "odbc", "opcache", "opencensus", "openswoole", "opentelemetry", "operator",
	"parallel", "parle", "pcntl", "pcov",
	"pdo", "pdo_dblib", "pdo_firebird", "pdo_mysql", "pdo_oci", "pdo_odbc", "pdo_pgsql",
	"pdo_snowflake", "pdo_sqlite", "pdo_sqlsrv", "pgsql", "phalcon", "php_trie", "phpy",
	"pkcs11", "pq", "propro", "protobuf", "pspell", "psr",
	"raphf", "rdkafka", "redis", "relay",
	"saxon", "seasclick", "seaslog", "shmop", "simdjson", "simplexml", "smbclient", "snappy",
	"snmp", "snuffleupagus", "soap", "sockets", "sodium", "solr", "sourceguardian", "spx", "sqlsrv",
	"ssh2", "stomp", "swoole", "sync", "sysvmsg", "sysvsem", "sysvshm",
	"tensor", "tideways", "tidy", "timezonedb", "translit",
	"uopz", "uploadprogress", "uuid", "uv",
	"vips", "vld",
	"xattr", "xdebug", "xdiff", "xhprof", "xlswriter", "xmldiff", "xmlrpc", "xpass", "xsl",
	"yac", "yaml", "yar",
	"zephir_parser", "zip", "zmq", "zookeeper", "zstd",
}

// KnownPHPExtensions returns a sorted list of all PHP extensions supported by
// install-php-extensions.
func KnownPHPExtensions() []string {
	exts := make([]string, len(ipeExtensions))
	copy(exts, ipeExtensions)
	sort.Strings(exts)
	return exts
}

// builtinExtensions are always compiled into PHP — no installation step needed.
// These extensions are either statically compiled into the PHP binary or are
// deeply integrated and cannot be built as a separate shared extension via
// docker-php-ext-install (e.g. opcache, tokenizer).
var builtinExtensions = map[string]bool{
	"json":      true,
	"hash":      true,
	"openssl":   true,
	"sodium":    true,
	"filter":    true,
	"ctype":     true,
	"session":   true,
	"pcre":      true,
	"spl":       true,
	"standard":  true,
	"tokenizer": true, // requires Zend parser source files not present after PHP is compiled
	// Note: opcache is NOT listed here — IPE handles enabling it correctly via
	// docker-php-ext-enable, and we always write an opcache.ini regardless.
}

// generatePHPDockerfile generates a Dockerfile for a PHP site, installing all
// required extensions via install-php-extensions (https://github.com/mlocati/docker-php-extension-installer).
// The output is deterministic in (php_version, sorted extensions) so two sites
// with the same fingerprint produce byte-identical Dockerfiles and share the
// same `srv-php:<hash>` image. Buildkit cache mounts speed up extension
// installs by reusing /var/cache/apk across builds.
func generatePHPDockerfile(info *PHPSiteInfo) string {
	image := PHPImageTag(info.PHPVersion)

	// Filter out built-in extensions — they are already compiled into PHP.
	var exts []string
	for _, ext := range info.Extensions {
		if !builtinExtensions[ext] {
			exts = append(exts, ext)
		}
	}
	sort.Strings(exts)

	var sb strings.Builder
	sb.WriteString("# syntax=docker/dockerfile:1.6\n")
	sb.WriteString("# Generated by srv - PHP site Dockerfile\n")
	fmt.Fprintf(&sb, "FROM %s\n\n", image)

	// Install extensions and composer via install-php-extensions (IPE).
	// IPE resolves all Alpine packages, PECL vs bundled, and configure flags automatically.
	// @composer is always included so that `srv composer` works inside the container.
	sb.WriteString("# Install PHP extensions and composer\n")
	sb.WriteString("ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/\n")
	// Cache mounts: /var/cache/apk speeds up alpine package fetches across
	// sibling builds; /tmp/ipe-build keeps IPE's tarball cache.
	sb.WriteString("RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \\\n")
	sb.WriteString("    --mount=type=cache,target=/tmp/ipe-build,sharing=locked \\\n")
	sb.WriteString("    install-php-extensions \\\n    @composer")
	for _, ext := range exts {
		sb.WriteString(" \\\n    " + ext)
	}
	sb.WriteString("\n\n")

	// Configure opcache — always write sensible defaults. opcache is included in
	// every PHP-FPM image but must be explicitly enabled via ini.
	sb.WriteString("# Configure opcache\n")
	sb.WriteString("RUN echo \"opcache.enable=1\" >> /usr/local/etc/php/conf.d/opcache.ini \\\n")
	sb.WriteString("    && echo \"opcache.enable_cli=0\" >> /usr/local/etc/php/conf.d/opcache.ini \\\n")
	sb.WriteString("    && echo \"opcache.memory_consumption=128\" >> /usr/local/etc/php/conf.d/opcache.ini \\\n")
	sb.WriteString("    && echo \"opcache.max_accelerated_files=10000\" >> /usr/local/etc/php/conf.d/opcache.ini \\\n")
	sb.WriteString("    && echo \"opcache.validate_timestamps=1\" >> /usr/local/etc/php/conf.d/opcache.ini\n\n")

	fmt.Fprintf(&sb, "WORKDIR %s\n", constants.PHPDockerRootPath)

	return sb.String()
}

// PHPImageFingerprint returns a deterministic 12-char hex tag derived from
// (php_version, sorted non-builtin extensions). Sites with the same fingerprint
// share one prebuilt image (`srv-php:<hash>`) instead of each rebuilding from
// scratch. Built-in extensions are excluded so two sites differing only in a
// no-op `--php-extensions "+pdo"` still match.
func PHPImageFingerprint(info *PHPSiteInfo) string {
	var exts []string
	for _, ext := range info.Extensions {
		if !builtinExtensions[ext] {
			exts = append(exts, ext)
		}
	}
	sort.Strings(exts)
	h := sha256.New()
	_, _ = fmt.Fprintf(h, "v1|%s|%s", info.PHPVersion, strings.Join(exts, ","))
	return fmt.Sprintf("srv-php:%x", h.Sum(nil)[:6])
}
