// Package site — php_render.go renders the per-site PHP Dockerfile and
// exposes the install-php-extensions catalogue used to validate and
// auto-complete extension names. With the FrankenPHP runtime there is no
// nginx.conf, no php.ini drop-in, and no php-fpm.conf — those concerns are
// either handled inside the FrankenPHP image (Caddy + embedded PHP) or live
// inside the user's project (e.g. their own conf.d/*.ini overrides loaded via
// FrankenPHP's standard PHP config path).
package site

import (
	"fmt"
	"sort"
	"strings"

	"github.com/stubbedev/srv/internal/constants"
)

// =============================================================================
// Extension catalogue (install-php-extensions)
// =============================================================================

// ipeExtensions is the full list of PHP extensions supported by
// install-php-extensions (https://github.com/mlocati/docker-php-extension-installer).
// All dependency resolution (Alpine packages, PECL vs bundled, configure flags)
// is handled automatically by IPE at build time.
var ipeExtensions = []string{
	"amqp", "apcu", "apcu_bc", "ast",
	"bcmath", "bitset", "blackfire", "brotli", "bz2",
	"calendar", "cassandra", "cmark", "csv",
	"dba", "ddtrace", "decimal", "ds",
	"ecma_intl", "enchant", "ev", "event", "excimer", "exif",
	"ffi", "ftp",
	"gd", "gearman", "geoip", "geos", "geospatial", "gettext", "gmagick", "gmp", "gnupg", "grpc",
	"http",
	"igbinary", "imagick", "imap", "inotify", "intl", "ion", "ioncube_loader", "ip2location",
	"jsmin", "json_post", "jsonpath", "judy",
	"ldap", "luasandbox", "lz4", "lzf",
	"mailparse", "maxminddb", "mbstring", "mcrypt", "md4c", "memcache", "memcached", "memprof",
	"mongodb", "msgpack", "mysqli",
	"oauth", "oci8", "odbc", "opcache", "opencensus", "openswoole", "opentelemetry", "operator",
	"parallel", "parle", "pcntl", "pcov",
	"pdo", "pdo_dblib", "pdo_firebird", "pdo_mysql", "pdo_oci", "pdo_odbc", "pdo_pgsql",
	"pdo_snowflake", "pdo_sqlite", "pdo_sqlsrv", "pgsql", "phalcon", "php_trie", "phpy",
	"pkcs11", "pq", "propro", "protobuf", "pspell", "psr",
	"raphf", "rdkafka", "redis", "relay",
	"saxon", "seasclick", "seaslog", "shmop", "simdjson", "simplexml", "smbclient", "snappy",
	"snmp", "snuffleupagus", "soap", "sockets", "sodium", "solr", "sourceguardian", "spx", "sqlsrv",
	"ssh2", "stomp", "swoole", "sync", "sysvmsg", "sysvsem", "sysvshm",
	"tensor", "tideways", "tidy", "timezonedb", "translit",
	"uopz", "uploadprogress", "uuid", "uv",
	"vips", "vld",
	"xattr", "xdebug", "xdiff", "xhprof", "xlswriter", "xmldiff", "xmlrpc", "xpass", "xsl",
	"yac", "yaml", "yar",
	"zephir_parser", "zip", "zmq", "zookeeper", "zstd",
}

// KnownPHPExtensions returns a sorted list of all PHP extensions supported by
// install-php-extensions.
func KnownPHPExtensions() []string {
	exts := make([]string, len(ipeExtensions))
	copy(exts, ipeExtensions)
	sort.Strings(exts)
	return exts
}

// builtinExtensions are always compiled into PHP — no installation step needed.
// Skipping these keeps the Dockerfile clean and avoids spurious `install-php-extensions`
// invocations for no-ops.
var builtinExtensions = map[string]bool{
	"json":      true,
	"hash":      true,
	"openssl":   true,
	"sodium":    true,
	"filter":    true,
	"ctype":     true,
	"session":   true,
	"pcre":      true,
	"spl":       true,
	"standard":  true,
	"tokenizer": true, // requires Zend parser source files not present after PHP is compiled
}

// IsBuiltinPHPExtension reports whether ext ships pre-compiled into the base
// FrankenPHP/PHP image.
func IsBuiltinPHPExtension(ext string) bool {
	return builtinExtensions[ext]
}

// nonBuiltinExtensions returns the input list filtered to extensions that
// install-php-extensions actually needs to install.
func nonBuiltinExtensions(exts []string) []string {
	out := make([]string, 0, len(exts))
	for _, e := range exts {
		if !builtinExtensions[e] {
			out = append(out, e)
		}
	}
	return out
}

// =============================================================================
// Dockerfile generation (FrankenPHP)
// =============================================================================

// generatePHPDockerfile generates a Dockerfile for a PHP site. It builds FROM
// dunglas/frankenphp:php<version>-alpine and installs any requested PHP
// extensions via install-php-extensions. Buildkit cache mounts speed up
// extension installs by reusing /var/cache/apk and IPE's tarball cache across
// builds.
func generatePHPDockerfile(info *PHPSiteInfo) string {
	image := FrankenPHPBaseImage(info.PHPVersion)
	exts := nonBuiltinExtensions(info.Extensions)
	sort.Strings(exts)

	var sb strings.Builder
	sb.WriteString("# syntax=docker/dockerfile:1.6\n")
	sb.WriteString("# Generated by srv - PHP site Dockerfile (FrankenPHP runtime)\n")
	fmt.Fprintf(&sb, "FROM %s\n\n", image)

	// install-php-extensions handles every PHP extension on the IPE catalogue.
	// @composer is always included so `srv composer` works inside the container.
	sb.WriteString("# Install PHP extensions and composer\n")
	sb.WriteString("ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/\n")
	sb.WriteString("RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \\\n")
	sb.WriteString("    --mount=type=cache,target=/tmp/ipe-build,sharing=locked \\\n")
	sb.WriteString("    install-php-extensions \\\n    @composer")
	for _, ext := range exts {
		sb.WriteString(" \\\n    " + ext)
	}
	sb.WriteString("\n\n")

	// Sensible opcache defaults — opcache ships in the FrankenPHP image but is
	// not enabled by default for non-CLI requests.
	sb.WriteString("# Configure opcache\n")
	sb.WriteString("RUN echo \"opcache.enable=1\" >> /usr/local/etc/php/conf.d/opcache.ini \\\n")
	sb.WriteString("    && echo \"opcache.enable_cli=0\" >> /usr/local/etc/php/conf.d/opcache.ini \\\n")
	sb.WriteString("    && echo \"opcache.memory_consumption=128\" >> /usr/local/etc/php/conf.d/opcache.ini \\\n")
	sb.WriteString("    && echo \"opcache.max_accelerated_files=10000\" >> /usr/local/etc/php/conf.d/opcache.ini \\\n")
	sb.WriteString("    && echo \"opcache.validate_timestamps=1\" >> /usr/local/etc/php/conf.d/opcache.ini\n\n")

	// Tuned-for-dev defaults: large body limits, long timeouts. Users can
	// override by dropping their own ini into the project root and copying it
	// in via a Dockerfile.srv override (see plan 2g).
	sb.WriteString("# Development-friendly php.ini defaults\n")
	sb.WriteString("RUN echo \"memory_limit=2G\" >> /usr/local/etc/php/conf.d/zz-srv-dev.ini \\\n")
	sb.WriteString("    && echo \"upload_max_filesize=2G\" >> /usr/local/etc/php/conf.d/zz-srv-dev.ini \\\n")
	sb.WriteString("    && echo \"post_max_size=2G\" >> /usr/local/etc/php/conf.d/zz-srv-dev.ini \\\n")
	sb.WriteString("    && echo \"max_execution_time=300\" >> /usr/local/etc/php/conf.d/zz-srv-dev.ini \\\n")
	sb.WriteString("    && echo \"max_input_time=300\" >> /usr/local/etc/php/conf.d/zz-srv-dev.ini \\\n")
	sb.WriteString("    && echo \"max_input_vars=10000\" >> /usr/local/etc/php/conf.d/zz-srv-dev.ini\n\n")

	fmt.Fprintf(&sb, "WORKDIR %s\n", constants.FrankenPHPAppDir)

	return sb.String()
}
