package site

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stubbedev/srv/internal/config"
)

// A reload whose derivable steps failed must not record the metadata hash:
// the short-circuit would then skip every later reload and keep the broken
// TLS/DNS state applied until the metadata itself changed.
func TestReloadDoesNotPersistHashWhenStepsFail(t *testing.T) {
	root := withSRVRoot(t)
	cfg, err := config.Load()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(cfg.TraefikDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := WriteSiteMetadata("d", SiteMetadata{
		Type:        SiteTypeStatic,
		Domains:     []string{"d.test"},
		ProjectPath: t.TempDir(),
		Port:        80,
		IsLocal:     true,
	}); err != nil {
		t.Fatal(err)
	}
	// Block cert issuance: the site's cert directory cannot be created.
	if err := os.WriteFile(cfg.SiteCertsDir("d"), []byte("not a dir"), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := Reload("d")
	if err != nil {
		t.Fatalf("reload with a failed cert step: %v", err)
	}
	if res.Skipped {
		t.Fatal("first reload cannot be skipped")
	}
	if len(res.Warnings) == 0 {
		t.Fatal("expected the cert failure to surface as a warning")
	}

	res2, err := Reload("d")
	if err != nil {
		t.Fatalf("second reload: %v", err)
	}
	if res2.Skipped {
		t.Error("hash was persisted despite failed steps — later reloads short-circuit on broken state")
	}
	_ = root
}

// Dockerfile-site compose files are regenerated by Reload: they used to be
// written only by `srv add`, so every later mutation (alias, volume, network,
// listener) silently never reached the container's labels or mounts.
func TestReloadRegeneratesDockerfileSiteCompose(t *testing.T) {
	withSRVRoot(t)
	cfg, err := config.Load()
	if err != nil {
		t.Fatal(err)
	}
	project := t.TempDir()
	if err := os.WriteFile(filepath.Join(project, "Dockerfile"), []byte("FROM nginx:alpine\nEXPOSE 8080\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := WriteSiteMetadata("df", SiteMetadata{
		Type:           SiteTypeDockerfile,
		Domains:        []string{"df.test"},
		ProjectPath:    project,
		Port:           8080,
		DockerfilePort: 8080,
		ServiceName:    "srv-df-app",
	}); err != nil {
		t.Fatal(err)
	}

	res, err := Reload("df")
	if err != nil {
		t.Fatalf("initial reload: %v", err)
	}
	if !res.NeedsRestart {
		t.Error("dockerfile site reload should require a restart")
	}
	compose := SiteComposePath(cfg, "df")
	data, err := os.ReadFile(compose)
	if err != nil {
		t.Fatalf("compose file missing: %v", err)
	}
	if !strings.Contains(string(data), "df.test") {
		t.Errorf("compose does not carry the site domain: %q", data)
	}

	// A metadata mutation must reach the regenerated compose file.
	meta, err := ReadSiteMetadata("df")
	if err != nil {
		t.Fatal(err)
	}
	meta.Domains = append(meta.Domains, "www.df.test")
	if err := WriteSiteMetadata("df", *meta); err != nil {
		t.Fatal(err)
	}
	if _, err := Reload("df"); err != nil {
		t.Fatalf("reload after mutation: %v", err)
	}
	data, err = os.ReadFile(compose)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "www.df.test") {
		t.Errorf("alias never reached the regenerated compose file: %q", data)
	}
}

// A failed artifact write must not leave a half-registered site behind:
// metadata.yml is the registration record, so `srv add` can be retried.
func TestAddArtifactFailureLeavesNoHalfRegisteredSite(t *testing.T) {
	withSRVRoot(t)
	cfg, err := config.Load()
	if err != nil {
		t.Fatal(err)
	}
	project := t.TempDir()
	if err := os.WriteFile(filepath.Join(project, "docker-compose.yml"), []byte("services: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// The Traefik conf dir cannot be created: the artifact write fails.
	if err := os.MkdirAll(cfg.TraefikDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(cfg.TraefikConfDir(), []byte("not a dir"), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := Add(AddOptions{Path: project, Domain: "half.test", Start: false}); err == nil {
		t.Fatal("expected the artifact write failure to fail Add")
	}
	if Exists("half") {
		t.Error("site registered despite failed artifacts")
	}
	if meta, err := ReadSiteMetadata("half"); meta != nil || err != nil {
		t.Errorf("metadata left behind: %v, %v", meta, err)
	}
}
