// Package site handles site management operations.
package site

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseEnv(t *testing.T) {
	tests := []struct {
		name           string
		content        string
		expectedDomain string
		expectedLocal  bool
	}{
		{
			name: "basic production domain",
			content: `DEPLOY_DOMAIN=example.com
DEPLOY_LOCAL=false`,
			expectedDomain: "example.com",
			expectedLocal:  false,
		},
		{
			name: "local domain with true",
			content: `DEPLOY_DOMAIN=myapp.test
DEPLOY_LOCAL=true`,
			expectedDomain: "myapp.test",
			expectedLocal:  true,
		},
		{
			name: "local domain with 1",
			content: `DEPLOY_DOMAIN=myapp.test
DEPLOY_LOCAL=1`,
			expectedDomain: "myapp.test",
			expectedLocal:  true,
		},
		{
			name: "with comments and blank lines",
			content: `# This is a comment
DEPLOY_DOMAIN=test.example.com

# Another comment
DEPLOY_LOCAL=true
`,
			expectedDomain: "test.example.com",
			expectedLocal:  true,
		},
		{
			name: "with extra whitespace",
			content: `  DEPLOY_DOMAIN  =  example.com  
  DEPLOY_LOCAL  =  true  `,
			expectedDomain: "example.com",
			expectedLocal:  true,
		},
		{
			name:           "missing DEPLOY_LOCAL defaults to false",
			content:        `DEPLOY_DOMAIN=example.com`,
			expectedDomain: "example.com",
			expectedLocal:  false,
		},
		{
			name:           "empty file",
			content:        ``,
			expectedDomain: "",
			expectedLocal:  false,
		},
		{
			name: "invalid lines ignored",
			content: `invalid line without equals
DEPLOY_DOMAIN=example.com
another invalid line
DEPLOY_LOCAL=true`,
			expectedDomain: "example.com",
			expectedLocal:  true,
		},
		{
			name: "with network config",
			content: `# Generated by srv
DEPLOY_DOMAIN=myapp.test
DEPLOY_LOCAL=true
DEPLOY_NETWORK=srv_traefik`,
			expectedDomain: "myapp.test",
			expectedLocal:  true,
		},
		{
			name: "domain with equals in value",
			content: `DEPLOY_DOMAIN=example.com=extra
DEPLOY_LOCAL=false`,
			expectedDomain: "example.com=extra",
			expectedLocal:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Create temporary directory and env.site file
			tmpDir := t.TempDir()
			envPath := filepath.Join(tmpDir, "env.site")
			if err := os.WriteFile(envPath, []byte(tt.content), 0o644); err != nil {
				t.Fatalf("failed to write env.site: %v", err)
			}

			domain, isLocal := ParseEnv(tmpDir)

			if domain != tt.expectedDomain {
				t.Errorf("domain = %q, want %q", domain, tt.expectedDomain)
			}
			if isLocal != tt.expectedLocal {
				t.Errorf("isLocal = %v, want %v", isLocal, tt.expectedLocal)
			}
		})
	}
}

func TestParseEnvMissingFile(t *testing.T) {
	tmpDir := t.TempDir()
	// Don't create env.site file

	domain, isLocal := ParseEnv(tmpDir)

	if domain != "" {
		t.Errorf("expected empty domain for missing file, got %q", domain)
	}
	if isLocal != false {
		t.Errorf("expected isLocal=false for missing file, got %v", isLocal)
	}
}

func TestIsLocalDomain(t *testing.T) {
	tests := []struct {
		domain   string
		expected bool
	}{
		{"myapp.test", true},
		{"myapp.localhost", true},
		{"example.com", false},
		{"test.example.com", false},
		{"myapp.dev", false},
		{"foo.test", true},
		{"foo.bar.test", true},
		{"test", false},       // No leading dot
		{"testdomain", false}, // Not a suffix
	}

	for _, tt := range tests {
		t.Run(tt.domain, func(t *testing.T) {
			result := IsLocalDomain(tt.domain)
			if result != tt.expected {
				t.Errorf("IsLocalDomain(%q) = %v, want %v", tt.domain, result, tt.expected)
			}
		})
	}
}

func TestSanitizeName(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"MyProject", "myproject"},
		{"my project", "my-project"},
		{"/path/to/my-app", "my-app"},
		{"My App Name", "my-app-name"},
		{"UPPERCASE", "uppercase"},
		{"already-valid", "already-valid"},
		{"/home/user/projects/SomeApp", "someapp"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			result := SanitizeName(tt.input)
			if result != tt.expected {
				t.Errorf("SanitizeName(%q) = %q, want %q", tt.input, result, tt.expected)
			}
		})
	}
}

func TestResolvePath(t *testing.T) {
	// Test absolute path
	t.Run("absolute path", func(t *testing.T) {
		tmpDir := t.TempDir()
		result, err := ResolvePath(tmpDir)
		if err != nil {
			t.Fatalf("ResolvePath failed: %v", err)
		}
		if result != tmpDir {
			t.Errorf("ResolvePath(%q) = %q, want %q", tmpDir, result, tmpDir)
		}
	})

	// Test relative path
	t.Run("relative path", func(t *testing.T) {
		result, err := ResolvePath(".")
		if err != nil {
			t.Fatalf("ResolvePath failed: %v", err)
		}
		if !filepath.IsAbs(result) {
			t.Errorf("expected absolute path, got %q", result)
		}
	})

	// Test non-existent path returns absolute path without error
	t.Run("non-existent path", func(t *testing.T) {
		result, err := ResolvePath("/path/that/does/not/exist")
		if err != nil {
			t.Fatalf("ResolvePath failed: %v", err)
		}
		if result != "/path/that/does/not/exist" {
			t.Errorf("expected absolute path for non-existent, got %q", result)
		}
	})
}

func TestFindComposeFile(t *testing.T) {
	tests := []struct {
		name     string
		files    []string
		expected string
		wantErr  bool
	}{
		{
			name:     "docker-compose.yml",
			files:    []string{"docker-compose.yml"},
			expected: "docker-compose.yml",
		},
		{
			name:     "docker-compose.yaml",
			files:    []string{"docker-compose.yaml"},
			expected: "docker-compose.yaml",
		},
		{
			name:     "compose.yml",
			files:    []string{"compose.yml"},
			expected: "compose.yml",
		},
		{
			name:     "compose.yaml",
			files:    []string{"compose.yaml"},
			expected: "compose.yaml",
		},
		{
			name:     "prefers docker-compose.yml",
			files:    []string{"docker-compose.yml", "compose.yml"},
			expected: "docker-compose.yml",
		},
		{
			name:    "no compose file",
			files:   []string{"README.md", "main.go"},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			for _, f := range tt.files {
				path := filepath.Join(tmpDir, f)
				if err := os.WriteFile(path, []byte("test"), 0o644); err != nil {
					t.Fatalf("failed to create file %s: %v", f, err)
				}
			}

			result, err := FindComposeFile(tmpDir)
			if tt.wantErr {
				if err == nil {
					t.Errorf("expected error, got nil")
				}
				return
			}
			if err != nil {
				t.Fatalf("FindComposeFile failed: %v", err)
			}
			expectedPath := filepath.Join(tmpDir, tt.expected)
			if result != expectedPath {
				t.Errorf("FindComposeFile() = %q, want %q", result, expectedPath)
			}
		})
	}
}

func TestParseComposeFile(t *testing.T) {
	t.Run("valid compose file with services", func(t *testing.T) {
		tmpDir := t.TempDir()
		content := `services:
  web:
    image: nginx:latest
    labels:
      - traefik.enable=true
  db:
    image: postgres:15
`
		composePath := filepath.Join(tmpDir, "docker-compose.yml")
		if err := os.WriteFile(composePath, []byte(content), 0o644); err != nil {
			t.Fatalf("failed to write compose file: %v", err)
		}

		compose, err := ParseComposeFile(composePath)
		if err != nil {
			t.Fatalf("ParseComposeFile failed: %v", err)
		}

		if len(compose.Services) != 2 {
			t.Errorf("expected 2 services, got %d", len(compose.Services))
		}
		if _, ok := compose.Services["web"]; !ok {
			t.Errorf("expected 'web' service")
		}
		if _, ok := compose.Services["db"]; !ok {
			t.Errorf("expected 'db' service")
		}
	})

	t.Run("compose file with map labels", func(t *testing.T) {
		tmpDir := t.TempDir()
		content := `services:
  web:
    image: nginx:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.web.rule: "Host('example.com')"
`
		composePath := filepath.Join(tmpDir, "docker-compose.yml")
		if err := os.WriteFile(composePath, []byte(content), 0o644); err != nil {
			t.Fatalf("failed to write compose file: %v", err)
		}

		compose, err := ParseComposeFile(composePath)
		if err != nil {
			t.Fatalf("ParseComposeFile failed: %v", err)
		}

		if len(compose.Services) != 1 {
			t.Errorf("expected 1 service, got %d", len(compose.Services))
		}
	})
}

func TestGetServiceNames(t *testing.T) {
	tmpDir := t.TempDir()
	content := `services:
  web:
    image: nginx
  api:
    image: node
  db:
    image: postgres
`
	composePath := filepath.Join(tmpDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write compose file: %v", err)
	}

	names, err := GetServiceNames(composePath)
	if err != nil {
		t.Fatalf("GetServiceNames failed: %v", err)
	}

	if len(names) != 3 {
		t.Errorf("expected 3 service names, got %d", len(names))
	}

	// Check all services are present (order may vary due to map iteration)
	expected := map[string]bool{"web": true, "api": true, "db": true}
	for _, name := range names {
		if !expected[name] {
			t.Errorf("unexpected service name: %s", name)
		}
	}
}

func TestEnsureSiteComposeInclude(t *testing.T) {
	t.Run("adds include to file without include section", func(t *testing.T) {
		tmpDir := t.TempDir()
		content := `services:
  web:
    image: nginx
`
		composePath := filepath.Join(tmpDir, "docker-compose.yml")
		if err := os.WriteFile(composePath, []byte(content), 0o644); err != nil {
			t.Fatalf("failed to write compose file: %v", err)
		}

		added, err := EnsureSiteComposeInclude(composePath)
		if err != nil {
			t.Fatalf("EnsureSiteComposeInclude failed: %v", err)
		}
		if !added {
			t.Error("expected include to be added")
		}

		// Read and verify the file
		data, _ := os.ReadFile(composePath)
		if !containsString(string(data), "docker-compose.site.yml") {
			t.Error("expected file to contain docker-compose.site.yml")
		}
	})

	t.Run("does not duplicate existing include", func(t *testing.T) {
		tmpDir := t.TempDir()
		content := `include:
  - docker-compose.site.yml
services:
  web:
    image: nginx
`
		composePath := filepath.Join(tmpDir, "docker-compose.yml")
		if err := os.WriteFile(composePath, []byte(content), 0o644); err != nil {
			t.Fatalf("failed to write compose file: %v", err)
		}

		added, err := EnsureSiteComposeInclude(composePath)
		if err != nil {
			t.Fatalf("EnsureSiteComposeInclude failed: %v", err)
		}
		if added {
			t.Error("expected include to not be added (already present)")
		}
	})

	t.Run("adds to existing include section", func(t *testing.T) {
		tmpDir := t.TempDir()
		content := `include:
  - other-compose.yml
services:
  web:
    image: nginx
`
		composePath := filepath.Join(tmpDir, "docker-compose.yml")
		if err := os.WriteFile(composePath, []byte(content), 0o644); err != nil {
			t.Fatalf("failed to write compose file: %v", err)
		}

		added, err := EnsureSiteComposeInclude(composePath)
		if err != nil {
			t.Fatalf("EnsureSiteComposeInclude failed: %v", err)
		}
		if !added {
			t.Error("expected include to be added")
		}

		// Read and verify both includes are present
		data, _ := os.ReadFile(composePath)
		content = string(data)
		if !containsString(content, "docker-compose.site.yml") {
			t.Error("expected file to contain docker-compose.site.yml")
		}
		if !containsString(content, "other-compose.yml") {
			t.Error("expected file to still contain other-compose.yml")
		}
	})
}

func TestRemoveSiteComposeInclude(t *testing.T) {
	t.Run("removes include from file", func(t *testing.T) {
		tmpDir := t.TempDir()
		content := `include:
  - docker-compose.site.yml
services:
  web:
    image: nginx
`
		composePath := filepath.Join(tmpDir, "docker-compose.yml")
		if err := os.WriteFile(composePath, []byte(content), 0o644); err != nil {
			t.Fatalf("failed to write compose file: %v", err)
		}

		removed, err := RemoveSiteComposeInclude(composePath)
		if err != nil {
			t.Fatalf("RemoveSiteComposeInclude failed: %v", err)
		}
		if !removed {
			t.Error("expected include to be removed")
		}

		// Verify the include is gone and services remain
		data, _ := os.ReadFile(composePath)
		content = string(data)
		if containsString(content, "docker-compose.site.yml") {
			t.Error("expected docker-compose.site.yml to be removed")
		}
		if !containsString(content, "services:") {
			t.Error("expected services to still be present")
		}
	})

	t.Run("returns false for non-existent file", func(t *testing.T) {
		tmpDir := t.TempDir()
		composePath := filepath.Join(tmpDir, "non-existent.yml")

		removed, err := RemoveSiteComposeInclude(composePath)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if removed {
			t.Error("expected removed to be false for non-existent file")
		}
	})

	t.Run("returns false when include not present", func(t *testing.T) {
		tmpDir := t.TempDir()
		content := `services:
  web:
    image: nginx
`
		composePath := filepath.Join(tmpDir, "docker-compose.yml")
		if err := os.WriteFile(composePath, []byte(content), 0o644); err != nil {
			t.Fatalf("failed to write compose file: %v", err)
		}

		removed, err := RemoveSiteComposeInclude(composePath)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if removed {
			t.Error("expected removed to be false when include not present")
		}
	})

	t.Run("preserves other includes", func(t *testing.T) {
		tmpDir := t.TempDir()
		content := `include:
  - other-compose.yml
  - docker-compose.site.yml
services:
  web:
    image: nginx
`
		composePath := filepath.Join(tmpDir, "docker-compose.yml")
		if err := os.WriteFile(composePath, []byte(content), 0o644); err != nil {
			t.Fatalf("failed to write compose file: %v", err)
		}

		removed, err := RemoveSiteComposeInclude(composePath)
		if err != nil {
			t.Fatalf("RemoveSiteComposeInclude failed: %v", err)
		}
		if !removed {
			t.Error("expected include to be removed")
		}

		// Verify only docker-compose.site.yml is removed
		data, _ := os.ReadFile(composePath)
		content = string(data)
		if containsString(content, "docker-compose.site.yml") {
			t.Error("expected docker-compose.site.yml to be removed")
		}
		if !containsString(content, "other-compose.yml") {
			t.Error("expected other-compose.yml to remain")
		}
	})
}

func TestWriteEnvFile(t *testing.T) {
	t.Run("writes correct content for local site", func(t *testing.T) {
		tmpDir := t.TempDir()

		err := WriteEnvFile(tmpDir, "myapp.test", true, "srv_traefik")
		if err != nil {
			t.Fatalf("WriteEnvFile failed: %v", err)
		}

		data, err := os.ReadFile(filepath.Join(tmpDir, "env.site"))
		if err != nil {
			t.Fatalf("failed to read env.site: %v", err)
		}

		content := string(data)
		if !containsString(content, "DEPLOY_DOMAIN=myapp.test") {
			t.Error("expected DEPLOY_DOMAIN=myapp.test")
		}
		if !containsString(content, "DEPLOY_LOCAL=true") {
			t.Error("expected DEPLOY_LOCAL=true")
		}
		if !containsString(content, "DEPLOY_NETWORK=srv_traefik") {
			t.Error("expected DEPLOY_NETWORK=srv_traefik")
		}
	})

	t.Run("writes correct content for production site", func(t *testing.T) {
		tmpDir := t.TempDir()

		err := WriteEnvFile(tmpDir, "example.com", false, "srv_traefik")
		if err != nil {
			t.Fatalf("WriteEnvFile failed: %v", err)
		}

		data, err := os.ReadFile(filepath.Join(tmpDir, "env.site"))
		if err != nil {
			t.Fatalf("failed to read env.site: %v", err)
		}

		content := string(data)
		if !containsString(content, "DEPLOY_DOMAIN=example.com") {
			t.Error("expected DEPLOY_DOMAIN=example.com")
		}
		if !containsString(content, "DEPLOY_LOCAL=false") {
			t.Error("expected DEPLOY_LOCAL=false")
		}
	})
}

// Helper function
func containsString(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(s) > 0 && containsSubstring(s, substr))
}

func containsSubstring(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}
