// Package site — static.go generates the on-disk artifacts for static
// (non-compose) sites: nginx.conf for the static container, the static-site
// docker-compose.yml, and the Traefik label builders that other site types
// (PHP, Node, …) reuse to declare their routes.
package site

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
	"github.com/stubbedev/srv/internal/platform"
	"github.com/stubbedev/srv/internal/traefik"
)

type StaticSiteOptions struct {
	SPA   bool // Enable SPA mode (fallback to index.html)
	Cache bool // Enable caching headers
	CORS  bool // Enable CORS headers
}

// generateStaticNginxConf generates nginx configuration based on options.
func generateStaticNginxConf(opts StaticSiteOptions) string {
	var config strings.Builder

	config.WriteString(`# Generated by srv - static site nginx config
# This file is yours to edit. "srv site regenerate" will reset it.
#
# Common customisations (uncomment to enable):
#
#   client_max_body_size 100M;     # Increase max upload / request body size

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml application/rss+xml application/atom+xml image/svg+xml;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
`)

	if opts.CORS {
		config.WriteString(`
    # CORS headers
    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, HEAD" always;
    add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization" always;

    # Handle preflight requests
    if ($request_method = 'OPTIONS') {
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, HEAD";
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization";
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 204;
    }
`)
	}

	config.WriteString(`
    # Block access to hidden files (dotfiles)
    location ~ /\. {
        deny all;
        return 404;
    }

    # Block access to sensitive file extensions
    location ~* \.(env|git|gitignore|gitmodules|htaccess|htpasswd|ds_store|yml|yaml|toml|ini|log|sh|sql|bak|swp|tmp)$ {
        deny all;
        return 404;
    }

    # Block access to common sensitive directories
    location ~* ^/(\.git|node_modules|vendor|\.svn|\.hg)/ {
        deny all;
        return 404;
    }

    # Serve static files
    location / {
`)

	if opts.SPA {
		config.WriteString(`        try_files $uri $uri/ /index.html =404;
`)
	} else {
		config.WriteString(`        try_files $uri $uri/ =404;
`)
	}

	config.WriteString(`    }

    # Custom 404 page
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
`)

	if opts.Cache {
		config.WriteString(`
    # Cache static assets
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
`)
	} else {
		config.WriteString(`
    # No caching (development mode)
    add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;
`)
	}

	config.WriteString(`}
`)

	return config.String()
}

// =============================================================================
// Static Site Configuration Types
// =============================================================================

// volumeConsistencyForHost returns "cached" on macOS so bind mounts trade
// strict host→container consistency for far better I/O throughput. Empty
// elsewhere (Docker ignores the field outside of Docker Desktop).
func volumeConsistencyForHost() string {
	if platform.IsDarwin() {
		return "cached"
	}
	return ""
}

// staticVolumeConfig represents a volume in docker-compose.
type staticVolumeConfig struct {
	Type        string `yaml:"type"`
	Source      string `yaml:"source"`
	Target      string `yaml:"target"`
	ReadOnly    bool   `yaml:"read_only"`
	Consistency string `yaml:"consistency,omitempty"`
}

// staticServiceConfig represents a service in docker-compose.
type staticServiceConfig struct {
	ContainerName string               `yaml:"container_name"`
	Image         string               `yaml:"image"`
	Volumes       []staticVolumeConfig `yaml:"volumes"`
	Labels        map[string]string    `yaml:"labels"`
	Networks      []string             `yaml:"networks"`
	Restart       string               `yaml:"restart"`
	HealthCheck   *staticHealthCheck   `yaml:"healthcheck,omitempty"`
}

// staticHealthCheck mirrors the compose healthcheck shape. Kept separate from
// phpHealthCheck so static sites don't pull in the FPM-specific helper.
type staticHealthCheck struct {
	Test        []string `yaml:"test"`
	Interval    string   `yaml:"interval,omitempty"`
	Timeout     string   `yaml:"timeout,omitempty"`
	StartPeriod string   `yaml:"start_period,omitempty"`
	Retries     int      `yaml:"retries,omitempty"`
}

// makeStaticHealthCheck builds a TCP-probe healthcheck for the given port.
// busybox `nc` ships in every alpine image srv currently uses.
func makeStaticHealthCheck(port int) *staticHealthCheck {
	return &staticHealthCheck{
		Test:        []string{"CMD-SHELL", fmt.Sprintf("nc -z 127.0.0.1 %d || exit 1", port)},
		Interval:    "30s",
		Timeout:     "3s",
		StartPeriod: "5s",
		Retries:     3,
	}
}

// staticNetworkConfig represents a network in docker-compose.
type staticNetworkConfig struct {
	Name     string `yaml:"name"`
	External bool   `yaml:"external"`
}

// staticComposeConfig represents a docker-compose.yml for static sites.
type staticComposeConfig struct {
	Name     string                         `yaml:"name,omitempty"`
	Services map[string]staticServiceConfig `yaml:"services"`
	Networks map[string]staticNetworkConfig `yaml:"networks"`
}

// buildStaticTraefikLabels builds Traefik labels for a static site.
func buildStaticTraefikLabels(name string, domains []string, isLocal, wildcard bool) map[string]string {
	labels := map[string]string{
		"traefik.enable": "true",
		fmt.Sprintf("traefik.http.routers.%s.rule", name):                      traefik.BuildHostRule(domains, wildcard),
		fmt.Sprintf("traefik.http.routers.%s.entrypoints", name):               "websecure",
		fmt.Sprintf("traefik.http.routers.%s.tls", name):                       "true",
		fmt.Sprintf("traefik.http.services.%s.loadbalancer.server.port", name): "80",
	}
	if !isLocal {
		labels[fmt.Sprintf("traefik.http.routers.%s.tls.certresolver", name)] = "letsencrypt"
	}
	return labels
}

// HasListener reports whether the supplied listener name is enabled on the
// site. Comparison is case-insensitive.
func HasListener(listeners []string, name string) bool {
	for _, l := range listeners {
		if strings.EqualFold(l, name) {
			return true
		}
	}
	return false
}

// addInternalListenerLabels appends labels for a plain-HTTP router on the
// `internal` entrypoint, sharing the site's existing Traefik service. Called
// when the site opts in via `listeners: [internal]`.
func addInternalListenerLabels(labels map[string]string, name string, domains []string, wildcard bool) {
	router := name + "-internal"
	labels[fmt.Sprintf("traefik.http.routers.%s.rule", router)] = traefik.BuildHostRule(domains, wildcard)
	labels[fmt.Sprintf("traefik.http.routers.%s.entrypoints", router)] = constants.EntryPointInternal
	labels[fmt.Sprintf("traefik.http.routers.%s.service", router)] = name
}

// StampSrvLabels attaches the dev.srv.site / dev.srv.type identity labels onto
// a container label map. Used by every site generator so `docker ps --filter
// label=dev.srv.site=<name>` works uniformly.
func StampSrvLabels(labels map[string]string, siteName, siteType string) {
	labels[constants.LabelSrvSite] = siteName
	labels[constants.LabelSrvType] = siteType
}

// buildStaticComposeConfig builds the docker-compose configuration for a static site.
func buildStaticComposeConfig(containerName, projectPath, nginxConfPath, networkName string, labels map[string]string) staticComposeConfig {
	return staticComposeConfig{
		Name: constants.ComposeProjectName,
		Services: map[string]staticServiceConfig{
			"web": {
				ContainerName: containerName,
				Image:         constants.ImageNginxAlpine,
				Volumes: []staticVolumeConfig{
					{
						Type:        "bind",
						Source:      projectPath,
						Target:      constants.NginxHTMLPath,
						ReadOnly:    true,
						Consistency: volumeConsistencyForHost(),
					},
					{
						Type:     "bind",
						Source:   nginxConfPath,
						Target:   constants.NginxDefaultConfPath,
						ReadOnly: true,
					},
				},
				Labels:      labels,
				Networks:    []string{constants.TraefikSubdir},
				Restart:     constants.RestartUnlessStopped,
				HealthCheck: makeStaticHealthCheck(80),
			},
		},
		Networks: map[string]staticNetworkConfig{
			constants.TraefikSubdir: {
				Name:     networkName,
				External: true,
			},
		},
	}
}

// writeFile writes content to path.
// If force is false and the file already exists, the write is skipped.
func writeFile(path string, content []byte, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return nil // file exists — user may have customized it
		}
	}
	return os.WriteFile(path, content, constants.FilePermDefault)
}

// WriteStaticSiteConfig writes the docker-compose.yml and nginx.conf for a static site.
// If force is false, existing files are left untouched so user edits are preserved.
func WriteStaticSiteConfig(name string, meta SiteMetadata, force bool) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	siteDir := SiteConfigDir(cfg, name)
	if err := os.MkdirAll(siteDir, constants.DirPermDefault); err != nil {
		return fmt.Errorf("failed to create site config directory: %w", err)
	}

	// Generate and write nginx config
	nginxConf := generateStaticNginxConf(StaticSiteOptions{
		SPA:   meta.SPA,
		Cache: meta.Cache,
		CORS:  meta.CORS,
	})
	nginxConfPath := SiteNginxConfPath(cfg, name)
	if err := writeFile(nginxConfPath, []byte(nginxConf), force); err != nil {
		return fmt.Errorf("failed to write nginx.conf: %w", err)
	}

	// Build and write docker-compose.yml
	containerName := generateStaticContainerName(name)
	labels := buildStaticTraefikLabels(name, meta.Domains, meta.IsLocal, meta.Wildcard)
	if HasListener(meta.Listeners, constants.ListenerInternal) {
		addInternalListenerLabels(labels, name, meta.Domains, meta.Wildcard)
	}
	StampSrvLabels(labels, name, string(meta.Type))
	composeConfig := buildStaticComposeConfig(containerName, meta.ProjectPath, nginxConfPath, meta.NetworkName, labels)

	data, err := yaml.Marshal(&composeConfig)
	if err != nil {
		return fmt.Errorf("failed to marshal compose config: %w", err)
	}

	header := fmt.Sprintf("# Generated by srv - static site\n# Project: %s\n#\n# This file is yours to edit. Changes take effect on next restart.\n\n", meta.ProjectPath)
	content := header + string(data)

	composePath := SiteComposePath(cfg, name)
	return writeFile(composePath, []byte(content), force)
}
