// Package site — static.go generates the on-disk artifacts for static
// (non-compose) sites: nginx.conf for the static container, the static-site
// docker-compose.yml, and the Traefik label builders that dockerfile-type
// sites reuse to declare their routes.
package site

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
	"github.com/stubbedev/srv/internal/nginx"
	"github.com/stubbedev/srv/internal/platform"
	"github.com/stubbedev/srv/internal/traefik"
)

type StaticSiteOptions struct {
	SPA   bool // Enable SPA mode (fallback to index.html)
	Cache bool // Enable caching headers
	CORS  bool // Enable CORS headers
}

// denyLocation builds a `location <match> { deny all; return 404; }` block used
// to lock down dotfiles, sensitive extensions, and sensitive directories.
func denyLocation(comment string, match ...string) nginx.Directive {
	return nginx.Block("location", match,
		nginx.Dir("deny", "all"),
		nginx.Dir("return", "404"),
	).WithComment(comment)
}

// generateStaticNginxConf generates nginx configuration based on options.
func generateStaticNginxConf(opts StaticSiteOptions) string {
	body := []nginx.Directive{
		nginx.Dir("listen", "80"),
		nginx.Dir("server_name", "_"),
		nginx.Dir("root", "/usr/share/nginx/html"),
		nginx.Dir("index", "index.html", "index.htm"),

		nginx.Dir("gzip", "on").WithComment("", "Gzip compression"),
		nginx.Dir("gzip_vary", "on"),
		nginx.Dir("gzip_min_length", "1024"),
		nginx.Dir("gzip_types",
			"text/plain", "text/css", "text/xml", "text/javascript",
			"application/javascript", "application/json", "application/xml",
			"application/rss+xml", "application/atom+xml", "image/svg+xml"),

		nginx.Dir("add_header", "X-Frame-Options", `"SAMEORIGIN"`, "always").WithComment("", "Security headers"),
		nginx.Dir("add_header", "X-Content-Type-Options", `"nosniff"`, "always"),
		nginx.Dir("add_header", "X-XSS-Protection", `"1; mode=block"`, "always"),
	}

	if opts.CORS {
		body = append(body,
			nginx.Dir("add_header", "Access-Control-Allow-Origin", `"*"`, "always").WithComment("", "CORS headers"),
			nginx.Dir("add_header", "Access-Control-Allow-Methods", `"GET, POST, OPTIONS, HEAD"`, "always"),
			nginx.Dir("add_header", "Access-Control-Allow-Headers", `"Origin, X-Requested-With, Content-Type, Accept, Authorization"`, "always"),
			nginx.Block("if", []string{"($request_method = 'OPTIONS')"},
				nginx.Dir("add_header", "Access-Control-Allow-Origin", `"*"`),
				nginx.Dir("add_header", "Access-Control-Allow-Methods", `"GET, POST, OPTIONS, HEAD"`),
				nginx.Dir("add_header", "Access-Control-Allow-Headers", `"Origin, X-Requested-With, Content-Type, Accept, Authorization"`),
				nginx.Dir("add_header", "Content-Length", "0"),
				nginx.Dir("add_header", "Content-Type", "text/plain"),
				nginx.Dir("return", "204"),
			).WithComment("Handle preflight requests"),
		)
	}

	body = append(body,
		denyLocation("Block access to hidden files (dotfiles)", "~", `/\.`),
		denyLocation("Block access to sensitive file extensions", "~*", `\.(env|git|gitignore|gitmodules|htaccess|htpasswd|ds_store|yml|yaml|toml|ini|log|sh|sql|bak|swp|tmp)$`),
		denyLocation("Block access to common sensitive directories", "~*", `^/(\.git|node_modules|vendor|\.svn|\.hg)/`),
	)

	tryFiles := nginx.Dir("try_files", "$uri", "$uri/", "=404")
	if opts.SPA {
		tryFiles = nginx.Dir("try_files", "$uri", "$uri/", "/index.html", "=404")
	}
	body = append(body,
		nginx.Block("location", []string{"/"}, tryFiles).WithComment("Serve static files"),
		nginx.Dir("error_page", "404", "/404.html").WithComment("", "Custom 404 page"),
		nginx.Block("location", []string{"=", "/404.html"}, nginx.Dir("internal")),
	)

	if opts.Cache {
		body = append(body,
			nginx.Block("location", []string{"~*", `\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$`},
				nginx.Dir("expires", "1y"),
				nginx.Dir("add_header", "Cache-Control", `"public, immutable"`),
			).WithComment("Cache static assets"),
		)
	} else {
		body = append(body,
			nginx.Dir("add_header", "Cache-Control", `"no-cache, no-store, must-revalidate"`, "always").WithComment("", "No caching (development mode)"),
			nginx.Dir("add_header", "Pragma", `"no-cache"`, "always"),
			nginx.Dir("add_header", "Expires", `"0"`, "always"),
		)
	}

	return nginx.Render(
		nginx.Block("server", nil, body...).WithComment(
			"Generated by srv - static site nginx config",
			`This file is yours to edit. "srv site regenerate" will reset it.`,
			"#",
			"Common customisations (uncomment to enable):",
			"#",
			"  client_max_body_size 100M;     # Increase max upload / request body size",
		),
	)
}

// =============================================================================
// Shared compose-generation types (used by static.go + dockerfile.go)
// =============================================================================

// volumeConsistencyForHost returns "cached" on macOS so bind mounts trade
// strict host→container consistency for far better I/O throughput. Empty
// elsewhere (Docker ignores the field outside of Docker Desktop).
func volumeConsistencyForHost() string {
	if platform.IsDarwin() {
		return "cached"
	}
	return ""
}

// composeVolume represents one bind mount in a generated docker-compose.yml.
type composeVolume struct {
	Type        string `yaml:"type"`
	Source      string `yaml:"source"`
	Target      string `yaml:"target"`
	ReadOnly    bool   `yaml:"read_only"`
	Consistency string `yaml:"consistency,omitempty"`
}

// composeBuild is the build context block; only set on dockerfile-type sites.
type composeBuild struct {
	Context    string `yaml:"context"`
	Dockerfile string `yaml:"dockerfile"`
}

// composeService represents one service in a generated docker-compose.yml.
// Image XOR Build is set depending on whether the site has a Dockerfile.
type composeService struct {
	ContainerName string              `yaml:"container_name"`
	Image         string              `yaml:"image,omitempty"`
	Build         *composeBuild       `yaml:"build,omitempty"`
	Volumes       []composeVolume     `yaml:"volumes,omitempty"`
	Labels        map[string]string   `yaml:"labels"`
	Networks      []string            `yaml:"networks"`
	Restart       string              `yaml:"restart"`
	HealthCheck   *composeHealthCheck `yaml:"healthcheck,omitempty"`
}

// composeHealthCheck mirrors the compose healthcheck shape.
type composeHealthCheck struct {
	Test        []string `yaml:"test"`
	Interval    string   `yaml:"interval,omitempty"`
	Timeout     string   `yaml:"timeout,omitempty"`
	StartPeriod string   `yaml:"start_period,omitempty"`
	Retries     int      `yaml:"retries,omitempty"`
}

// makeComposeHealthCheck builds a TCP-probe healthcheck for the given port.
// busybox `nc` ships in every alpine image srv currently uses.
func makeComposeHealthCheck(port int) *composeHealthCheck {
	return &composeHealthCheck{
		Test:        []string{"CMD-SHELL", fmt.Sprintf("nc -z 127.0.0.1 %d || exit 1", port)},
		Interval:    "30s",
		Timeout:     "3s",
		StartPeriod: "5s",
		Retries:     3,
	}
}

// composeNetwork represents one network entry in the top-level networks: map.
type composeNetwork struct {
	Name     string `yaml:"name"`
	External bool   `yaml:"external"`
}

// composeFile is the generated docker-compose.yml top-level shape.
type composeFile struct {
	Name     string                    `yaml:"name,omitempty"`
	Services map[string]composeService `yaml:"services"`
	Networks map[string]composeNetwork `yaml:"networks"`
}

// buildTraefikLabels emits the Traefik label set for a single-router site
// pointing at `port` inside the container. Used by both static (port 80)
// and dockerfile (port from EXPOSE) sites.
func buildTraefikLabels(name string, domains []string, isLocal, wildcard bool, port int) map[string]string {
	labels := map[string]string{
		"traefik.enable": "true",
		fmt.Sprintf("traefik.http.routers.%s.rule", name):                      traefik.BuildHostRule(domains, wildcard),
		fmt.Sprintf("traefik.http.routers.%s.entrypoints", name):               "websecure",
		fmt.Sprintf("traefik.http.routers.%s.tls", name):                       "true",
		fmt.Sprintf("traefik.http.services.%s.loadbalancer.server.port", name): fmt.Sprintf("%d", port),
	}
	if !isLocal {
		labels[fmt.Sprintf("traefik.http.routers.%s.tls.certresolver", name)] = "letsencrypt"
	}
	return labels
}

// HasListener reports whether the supplied listener name is enabled on the
// site. Comparison is case-insensitive.
func HasListener(listeners []string, name string) bool {
	for _, l := range listeners {
		if strings.EqualFold(l, name) {
			return true
		}
	}
	return false
}

// addInternalListenerLabels appends labels for a plain-HTTP router on the
// `internal` entrypoint, sharing the site's existing Traefik service. Called
// when the site opts in via `listeners: [internal]`.
func addInternalListenerLabels(labels map[string]string, name string, domains []string, wildcard bool) {
	router := name + "-internal"
	labels[fmt.Sprintf("traefik.http.routers.%s.rule", router)] = traefik.BuildHostRule(domains, wildcard)
	labels[fmt.Sprintf("traefik.http.routers.%s.entrypoints", router)] = constants.EntryPointInternal
	labels[fmt.Sprintf("traefik.http.routers.%s.service", router)] = name
}

// StampSrvLabels attaches the dev.srv.site / dev.srv.type identity labels onto
// a container label map. Used by every site generator so `docker ps --filter
// label=dev.srv.site=<name>` works uniformly.
func StampSrvLabels(labels map[string]string, siteName, siteType string) {
	labels[constants.LabelSrvSite] = siteName
	labels[constants.LabelSrvType] = siteType
}

// buildStaticComposeConfig builds the docker-compose configuration for a static site.
func buildStaticComposeConfig(project, containerName, projectPath, nginxConfPath, networkName string, labels map[string]string) composeFile {
	return composeFile{
		Name: project,
		Services: map[string]composeService{
			"web": {
				ContainerName: containerName,
				Image:         constants.ImageNginxAlpine,
				Volumes: []composeVolume{
					{
						Type:        "bind",
						Source:      projectPath,
						Target:      constants.NginxHTMLPath,
						ReadOnly:    true,
						Consistency: volumeConsistencyForHost(),
					},
					{
						Type:     "bind",
						Source:   nginxConfPath,
						Target:   constants.NginxDefaultConfPath,
						ReadOnly: true,
					},
				},
				Labels:      labels,
				Networks:    []string{constants.TraefikSubdir},
				Restart:     constants.RestartUnlessStopped,
				HealthCheck: makeComposeHealthCheck(80),
			},
		},
		Networks: map[string]composeNetwork{
			constants.TraefikSubdir: {
				Name:     networkName,
				External: true,
			},
		},
	}
}

// writeFile writes content to path.
// If force is false and the file already exists, the write is skipped.
func writeFile(path string, content []byte, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return nil // file exists — user may have customized it
		}
	}
	return os.WriteFile(path, content, constants.FilePermDefault)
}

// WriteStaticSiteConfig writes the docker-compose.yml and nginx.conf for a static site.
// If force is false, existing files are left untouched so user edits are preserved.
func WriteStaticSiteConfig(name string, meta SiteMetadata, force bool) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	siteDir := SiteConfigDir(cfg, name)
	if err := os.MkdirAll(siteDir, constants.DirPermDefault); err != nil {
		return fmt.Errorf("failed to create site config directory: %w", err)
	}

	// Generate and write nginx config
	nginxConf := generateStaticNginxConf(StaticSiteOptions{
		SPA:   meta.SPA,
		Cache: meta.Cache,
		CORS:  meta.CORS,
	})
	nginxConfPath := SiteNginxConfPath(cfg, name)
	if err := writeFile(nginxConfPath, []byte(nginxConf), force); err != nil {
		return fmt.Errorf("failed to write nginx.conf: %w", err)
	}

	// Build and write docker-compose.yml
	containerName := generateStaticContainerName(name)
	labels := buildTraefikLabels(name, meta.Domains, meta.IsLocal, meta.Wildcard, 80)
	if HasListener(meta.Listeners, constants.ListenerInternal) {
		addInternalListenerLabels(labels, name, meta.Domains, meta.Wildcard)
	}
	StampSrvLabels(labels, name, string(meta.Type))
	composeConfig := buildStaticComposeConfig(constants.ComposeProjectFor(name), containerName, meta.ProjectPath, nginxConfPath, meta.NetworkName, labels)

	data, err := yaml.Marshal(&composeConfig)
	if err != nil {
		return fmt.Errorf("failed to marshal compose config: %w", err)
	}

	header := fmt.Sprintf("# Generated by srv - static site\n# Project: %s\n#\n# This file is yours to edit. Changes take effect on next restart.\n\n", meta.ProjectPath)
	content := header + string(data)

	composePath := SiteComposePath(cfg, name)
	return writeFile(composePath, []byte(content), force)
}
