// Package metrics owns the opt-in prometheus + grafana stack used by
// `srv metrics`. Both services run as containers on the shared srv network so
// prometheus can scrape Traefik's existing /metrics endpoint directly by
// container name.
package metrics

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
	"github.com/stubbedev/srv/internal/platform"
)

const (
	// PrometheusImage is the prometheus image used by the metrics stack.
	PrometheusImage = "prom/prometheus:latest"
	// GrafanaImage is the grafana image used by the metrics stack.
	GrafanaImage = "grafana/grafana:latest"
	// PrometheusContainer is the container name for prometheus.
	PrometheusContainer = "srv-prometheus"
	// GrafanaContainer is the container name for grafana.
	GrafanaContainer = "srv-grafana"
	// GrafanaDomain is the local HTTPS hostname for the Grafana UI.
	GrafanaDomain = "grafana.local"
	// PrometheusDomain is the local HTTPS hostname for the Prometheus UI.
	PrometheusDomain = "prometheus.local"
	// ProxySiteName groups the metrics certs under one synthetic site dir
	// (~/.config/srv/sites/_proxy-metrics/certs/).
	ProxySiteName = "_proxy-metrics"
	// GrafanaHostPort is the loopback port the Grafana container binds on
	// Linux (host networking) so host-network Traefik can reach it. A
	// non-standard port avoids clashing with dev servers on :3000.
	GrafanaHostPort = 13000
	// PrometheusHostPort is the loopback port the Prometheus container binds
	// on Linux (host networking). Non-standard to avoid clashing with :9090.
	PrometheusHostPort = 19090
)

// Dir returns the on-disk directory for the metrics stack.
func Dir(cfg *config.Config) string {
	return filepath.Join(cfg.Root, "metrics")
}

// TraefikConfigPath returns the Traefik file-provider yaml that routes
// grafana.local + prometheus.local at the stack's two containers.
func TraefikConfigPath(cfg *config.Config) string {
	return filepath.Join(cfg.TraefikConfDir(), constants.ProxyConfigPrefix+"metrics"+constants.ExtYAML)
}

// WriteTraefikConfig emits the file-provider yaml so Traefik routes
// https://grafana.local and https://prometheus.local at the two containers.
// Both routers use TLS with mkcert-issued certs.
//
// On Linux, Traefik runs in host-network mode and cannot resolve the metrics
// container names, so it reaches them via the loopback host ports the compose
// stack publishes. On Mac/Windows, Traefik shares the srv network and routes
// to the containers by name.
func WriteTraefikConfig(cfg *config.Config) error {
	grafanaTarget := fmt.Sprintf("http://%s:3000", GrafanaContainer)
	prometheusTarget := fmt.Sprintf("http://%s:9090", PrometheusContainer)
	if platform.IsLinux() {
		grafanaTarget = fmt.Sprintf("http://127.0.0.1:%d", GrafanaHostPort)
		prometheusTarget = fmt.Sprintf("http://127.0.0.1:%d", PrometheusHostPort)
	}
	yamlBody := fmt.Sprintf(`# Generated by srv — metrics HTTPS routers
http:
  routers:
    metrics-grafana:
      rule: "Host(`+"`%s`"+`)"
      entryPoints: [websecure]
      service: metrics-grafana
      tls: {}
    metrics-prometheus:
      rule: "Host(`+"`%s`"+`)"
      entryPoints: [websecure]
      service: metrics-prometheus
      tls: {}
  services:
    metrics-grafana:
      loadBalancer:
        servers:
          - url: %s
    metrics-prometheus:
      loadBalancer:
        servers:
          - url: %s
`,
		GrafanaDomain,
		PrometheusDomain,
		grafanaTarget,
		prometheusTarget,
	)
	return os.WriteFile(TraefikConfigPath(cfg), []byte(yamlBody), constants.FilePermDefault)
}

// RemoveTraefikConfig deletes the file-provider yaml. Idempotent.
func RemoveTraefikConfig(cfg *config.Config) error {
	if err := os.Remove(TraefikConfigPath(cfg)); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// WriteStack renders the docker-compose.yml + prometheus.yml + grafana
// provisioning files into the metrics directory. Idempotent.
func WriteStack(cfg *config.Config) error {
	dir := Dir(cfg)
	provDir := filepath.Join(dir, "grafana-provisioning", "datasources")
	if err := os.MkdirAll(provDir, constants.DirPermDefault); err != nil {
		return fmt.Errorf("create metrics dir: %w", err)
	}

	if err := os.WriteFile(filepath.Join(dir, "prometheus.yml"), []byte(prometheusYAML()), constants.FilePermDefault); err != nil {
		return fmt.Errorf("write prometheus.yml: %w", err)
	}
	if err := os.WriteFile(filepath.Join(provDir, "prometheus.yml"), []byte(grafanaDatasourceYAML()), constants.FilePermDefault); err != nil {
		return fmt.Errorf("write grafana datasource: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte(composeYAML(cfg.NetworkName)), constants.FilePermDefault); err != nil {
		return fmt.Errorf("write compose: %w", err)
	}
	return nil
}

func prometheusYAML() string {
	// Linux: prometheus runs in host-network mode (like Traefik) and reaches
	// Traefik's metrics endpoint on the loopback. Mac/Windows: prometheus is
	// on the srv network and reaches Traefik by container name.
	traefikTarget := "srv-traefik:8080"
	if platform.IsLinux() {
		traefikTarget = "127.0.0.1:8080"
	}
	return fmt.Sprintf(`# Generated by srv — prometheus scrape config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets: ['%s']
`, traefikTarget)
}

func grafanaDatasourceYAML() string {
	// Linux: both services are host-networked, so grafana reaches prometheus
	// on the loopback. Mac/Windows: by container name on the srv network.
	promURL := "http://srv-prometheus:9090"
	if platform.IsLinux() {
		promURL = fmt.Sprintf("http://127.0.0.1:%d", PrometheusHostPort)
	}
	return fmt.Sprintf(`# Generated by srv — pre-wired Prometheus datasource
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: %s
    isDefault: true
    editable: true
`, promURL)
}

// composeYAML renders the metrics stack's docker-compose.yml. The Linux and
// Docker-Desktop shapes differ enough to warrant separate templates.
func composeYAML(networkName string) string {
	if platform.IsLinux() {
		return composeYAMLHost()
	}
	return composeYAMLBridge(networkName)
}

// composeYAMLHost renders the Linux stack. Both services use host networking —
// the same model srv uses for Traefik — so prometheus can scrape Traefik on
// 127.0.0.1:8080 and Traefik can route to the UIs on the loopback. Each UI is
// pinned to a loopback bind address + non-standard port so it is reachable by
// host-network Traefik without being exposed off-host or clashing with the
// usual :3000 / :9090 dev-server ports.
func composeYAMLHost() string {
	return fmt.Sprintf(`# Generated by srv — metrics stack (prometheus + grafana)
# Linux: host networking, matching how srv runs Traefik.
name: %s

services:
  prometheus:
    image: %s
    container_name: %s
    restart: unless-stopped
    network_mode: host
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.listen-address=127.0.0.1:%d"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    labels:
      - "%s=%s"
      - "%s=prometheus"

  grafana:
    image: %s
    container_name: %s
    restart: unless-stopped
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SERVER_ROOT_URL=https://%s
      - GF_SERVER_HTTP_ADDR=127.0.0.1
      - GF_SERVER_HTTP_PORT=%d
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
    labels:
      - "%s=%s"
      - "%s=grafana"
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:
`,
		constants.ComposeProjectName,
		PrometheusImage, PrometheusContainer, PrometheusHostPort,
		constants.LabelSrvSite, PrometheusDomain, constants.LabelSrvType,
		GrafanaImage, GrafanaContainer,
		GrafanaDomain, GrafanaHostPort,
		constants.LabelSrvSite, GrafanaDomain, constants.LabelSrvType,
	)
}

// composeYAMLBridge renders the Docker-Desktop (Mac/Windows) stack. There
// Traefik shares the srv bridge network, so the services join it and are
// reached by container name — no host networking, no published ports.
func composeYAMLBridge(networkName string) string {
	return fmt.Sprintf(`# Generated by srv — metrics stack (prometheus + grafana)
name: %s

services:
  prometheus:
    image: %s
    container_name: %s
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    labels:
      - "%s=%s"
      - "%s=prometheus"
    networks:
      - traefik

  grafana:
    image: %s
    container_name: %s
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SERVER_ROOT_URL=https://%s
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
    labels:
      - "%s=%s"
      - "%s=grafana"
    depends_on:
      - prometheus
    networks:
      - traefik

volumes:
  prometheus-data:
  grafana-data:

networks:
  traefik:
    name: %s
    external: true
`,
		constants.ComposeProjectName,
		PrometheusImage, PrometheusContainer,
		constants.LabelSrvSite, PrometheusDomain, constants.LabelSrvType,
		GrafanaImage, GrafanaContainer,
		GrafanaDomain,
		constants.LabelSrvSite, GrafanaDomain, constants.LabelSrvType,
		networkName,
	)
}
