// Package metrics owns the opt-in prometheus + grafana stack used by
// `srv metrics`. Both services run as containers on the shared srv network so
// prometheus can scrape Traefik's existing /metrics endpoint directly by
// container name.
package metrics

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/stubbedev/srv/internal/config"
	"github.com/stubbedev/srv/internal/constants"
)

const (
	// PrometheusImage is the prometheus image used by the metrics stack.
	PrometheusImage = "prom/prometheus:latest"
	// GrafanaImage is the grafana image used by the metrics stack.
	GrafanaImage = "grafana/grafana:latest"
	// PrometheusContainer is the container name for prometheus.
	PrometheusContainer = "srv-prometheus"
	// GrafanaContainer is the container name for grafana.
	GrafanaContainer = "srv-grafana"
	// GrafanaPort is the host-exposed port for the Grafana UI.
	GrafanaPort = "3030"
	// PrometheusPort is the host-exposed port for the Prometheus UI.
	PrometheusPort = "9090"
)

// Dir returns the on-disk directory for the metrics stack.
func Dir(cfg *config.Config) string {
	return filepath.Join(cfg.Root, "metrics")
}

// WriteStack renders the docker-compose.yml + prometheus.yml + grafana
// provisioning files into the metrics directory. Idempotent.
func WriteStack(cfg *config.Config) error {
	dir := Dir(cfg)
	provDir := filepath.Join(dir, "grafana-provisioning", "datasources")
	if err := os.MkdirAll(provDir, constants.DirPermDefault); err != nil {
		return fmt.Errorf("create metrics dir: %w", err)
	}

	if err := os.WriteFile(filepath.Join(dir, "prometheus.yml"), []byte(prometheusYAML()), constants.FilePermDefault); err != nil {
		return fmt.Errorf("write prometheus.yml: %w", err)
	}
	if err := os.WriteFile(filepath.Join(provDir, "prometheus.yml"), []byte(grafanaDatasourceYAML()), constants.FilePermDefault); err != nil {
		return fmt.Errorf("write grafana datasource: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte(composeYAML(cfg.NetworkName)), constants.FilePermDefault); err != nil {
		return fmt.Errorf("write compose: %w", err)
	}
	return nil
}

func prometheusYAML() string {
	// On Linux, Traefik runs in host network mode and exposes :8080 on the
	// host. On Mac/Windows, Traefik is on the srv network as `srv-traefik`
	// and is reachable by container name.
	traefikTarget := "srv-traefik:8080"
	if runtime.GOOS == "linux" {
		traefikTarget = "host.docker.internal:8080"
	}
	return fmt.Sprintf(`# Generated by srv — prometheus scrape config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets: ['%s']
`, traefikTarget)
}

func grafanaDatasourceYAML() string {
	return `# Generated by srv — pre-wired Prometheus datasource
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://srv-prometheus:9090
    isDefault: true
    editable: true
`
}

func composeYAML(networkName string) string {
	extraHosts := ""
	if runtime.GOOS == "linux" {
		extraHosts = `
    extra_hosts:
      - "host.docker.internal:host-gateway"`
	}
	return fmt.Sprintf(`# Generated by srv — metrics stack (prometheus + grafana)
name: %s

services:
  prometheus:
    image: %s
    container_name: %s
    restart: unless-stopped
    ports:
      - "127.0.0.1:%s:9090"%s
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - traefik

  grafana:
    image: %s
    container_name: %s
    restart: unless-stopped
    ports:
      - "127.0.0.1:%s:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - traefik

volumes:
  prometheus-data:
  grafana-data:

networks:
  traefik:
    name: %s
    external: true
`,
		constants.ComposeProjectName,
		PrometheusImage, PrometheusContainer, PrometheusPort, extraHosts,
		GrafanaImage, GrafanaContainer, GrafanaPort,
		networkName,
	)
}
